function add_message()
    global snd
   
    myscreen=get(0,'screensize');
    figure('position',[4,(myscreen(4)-130),400,100],'menubar','none');
	
        
   uicontrol('style','edit',...
    	'units','normalized',...
    	'position', [.02 .02 .96 .96],...
    	'backgroundcolor',[1,1,1],...
    	'horizontalalignment','left',...
  		'string','',...
   	    'tag','add_message',...
    	'callback','snd.message{length(snd.message)+1}=get(findobj(gcf,''tag'',''add_message''),''string'');close;set(findobj(''tag'',''message''),''string'',snd.message);'); 


return;