function amp_off()
    global RA_16;
    invoke(RA_16,'halt');

   uicontrol('style','pushbutton',...
    'units','character',...
    'position', [75 2 15 2],...
    'horizontalalignment','center',...
    'string','Amp on',...
    'callback','amp_on'); 




return;
