function amp_on()
    global RA_16;
    invoke(RA_16,'run');

uicontrol('style','pushbutton',...
    'units','character',...
    'position', [75 2 15 2],...
    'horizontalalignment','center',...
    'string','Amp off',...
    'callback','amp_off'); 
return;
