function set_AS_ch()
    global RP_1 RP_2 pa5_1 pa5_2 RA_16  zbus vis rec snd;
    
    
    test_passed=invoke(RA_16,'GetTagVal','RA16four_loaded'); %% Kluge to check that RA_16 is running correct rco file
    if ~test_passed
        % Load correct RA_16
        invoke(RA_16,'halt');     
        invoke(RA_16,'ClearCOF');  
        currentdir=pwd;	
        RPVDS_path=strcat(currentdir,'\..\RPVDS');     
        if invoke(RA_16,'loadCOFsf',strcat(RPVDS_path,'\','RA16four'), 2)
            'RA16four loaded on RA16'
        else
            'error in loading RA16'
        end
        set_RA16;
    end
    
    
    if findobj(0,'tag','set_ch_params_win')>=1
        figure(findobj(0,'tag','set_ch_params_win'));     %% set the first window as active
      else    %%open a new window
        myscreen=get(0,'screensize');
        figure('position',[4,(myscreen(4)-430),575,400],...
            'menubar','none',...
            'tag','set_ch_params_win');

        c=get(gcf,'color');
        uicontrol('style','text',...
            'units','character',...
            'position', [34 26 60 2],...
            'backgroundcolor',c,...
            'string','Set Channel Parameters',...
            'horizontalalignment','left',...
            'fontweight','bold',...
            'fontsize',14);
	
        %%  Number of channels to record from
        uicontrol('style','text',...
            'units','character',...
            'position', [8 23.5 30 1],...
            'backgroundcolor',c,...
            'string','Number of Channels',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 23.5 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.numch,...
            'tag','numch',...
            'callback','set_rec'); 
	
        
        %% center of bandpass filter   
        uicontrol('style','text',...
            'units','character',...
            'position', [8 21.5 30 1],...
            'backgroundcolor',c,...
            'string','Center of BP Filter',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 21.5 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.filtcent,...
            'tag','filtcent',...
            'callback','set_rec'); 
	
	
     %% width of bandpass filter   
        uicontrol('style','text',...
            'units','character',...
            'position', [8 20 30 1],...
            'backgroundcolor',c,...
            'string','Width of BP Filter',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 20 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.filtwidth,...
            'tag','filtwidth',...
            'callback','set_rec'); 
	
     %% Channel gain 
        uicontrol('style','text',...
            'units','character',...
            'position', [8 18.5 30 1],...
            'backgroundcolor',c,...
            'string','Gain for Channels',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 18.5 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.gain,...
            'tag','gain',...
            'callback','set_rec'); 
	
	%% Channel shift 
        uicontrol('style','text',...
            'units','character',...
            'position', [8 17 30 1],...
            'backgroundcolor',c,...
            'string','Shift for Channels',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 17 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.shift,...
            'tag','shift',...
            'callback','set_rec'); 
        
	
        
	%% Channel Identity
        uicontrol('style','text',...
            'units','character',...
            'position', [4 14 8 1],...
            'backgroundcolor',c,...
            'string','Ch ID1',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [12 14 6 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.ChID1,...
            'tag','Ch_ID1',...
            'callback','set_rec'); 
        uicontrol('style','text',...
            'units','character',...
            'position', [4 12.5 8 1],...
            'backgroundcolor',c,...
            'string','Ch ID2',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [12 12.5 6 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.ChID2,...
            'tag','Ch_ID2',...
            'callback','set_rec'); 
        
        uicontrol('style','text',...
            'units','character',...
            'position', [4 11 8 1],...
            'backgroundcolor',c,...
            'string','Ch ID3',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [12 11 6 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.ChID3,...
            'tag','Ch_ID3',...
            'callback','set_rec'); 
        
        uicontrol('style','text',...
            'units','character',...
            'position', [4 9.5 8 1],...
            'backgroundcolor',c,...
            'string','Ch ID4',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [12 9.5 6 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.ChID4,...
            'tag','Ch_ID4',...
            'callback','set_rec'); 
	
        
        
	%% Channel Thresholds 
        uicontrol('style','text',...
            'units','character',...
            'position', [20 14 10 1],...
            'backgroundcolor',c,...
            'string','Thresh',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 14 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.thresh1,...
            'tag','thresh1',...
            'callback','set_rec'); 
        uicontrol('style','text',...
            'units','character',...
            'position', [20 12.5 10 1],...
            'backgroundcolor',c,...
            'string','Thresh',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 12.5 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.thresh2,...
            'tag','thresh2',...
            'callback','set_rec'); 
        uicontrol('style','text',...
            'units','character',...
            'position', [20 11 10 1],...
            'backgroundcolor',c,...
            'string','Thresh',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 11 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.thresh3,...
            'tag','thresh3',...
            'callback','set_rec'); 
        uicontrol('style','text',...
            'units','character',...
            'position', [20 9.5 10 1],...
            'backgroundcolor',c,...
            'string','Thresh',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','character',...
            'position', [30 9.5 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',rec.thresh4,...
            'tag','thresh4',...
            'callback','set_rec'); 
	
	
	%%  Channel for Oscilloscope
        uicontrol('style','text',...
            'units','character',...
            'position', [8 6 30 1],...
            'backgroundcolor',c,...
            'string','Osc Channel',...
            'horizontalalignment','left');
        uicontrol('style','popupmenu',...
            'units','character',...
            'position', [30 6 10 1.5],...
            'backgroundcolor',c,...
            'horizontalalignment','left',...
            'string',num2cell([1:rec.numch]),...
            'tag','OscCh',...
            'callback','set_rec'); 
	
        
	% % % %         uicontrol('style','popupmenu',...
	% % % %         'units','normalized',...
	% % % %         'position', [.43 .85 .06 .1],...
	% % % %         'backgroundcolor',c,...
	% % % %         'horizontalalignment','left',...
	% % % %         'string',num2cell([1:rec.numch]),...
	% % % %         'tag','dispch',...
	% % % %         'callback','set_disp_params;');
	
        
	%%  Get the default Values;
        uicontrol('style','pushbutton',...
            'units','character',...
            'position', [15 2 15 2],...
            'horizontalalignment','center',...
            'string','Default Values',...
            'callback','get_rec_defaults'); 
        
        uicontrol('style','pushbutton',...
            'units','character',...
            'position', [35 2 15 2],...
            'horizontalalignment','center',...
            'string','Close',...
            'callback','close_rec'); 
	
        uicontrol('style','pushbutton',...
            'units','character',...
            'position', [55 2 15 2],...
            'horizontalalignment','center',...
            'string','Set Thresh',...
            'callback','set_thresh'); 
        uicontrol('style','pushbutton',...
            'units','character',...
            'position', [75 2 15 2],...
            'horizontalalignment','center',...
            'string','Amp off',...
            'callback','amp_off'); 
	
        
        uicontrol('style','pushbutton',...
            'units','normalized',...
            'position', [.9 .95 .1 .051],...
            'horizontalalignment','center',...
            'string','Refresh',...
            'callback','close;set_AS_ch;'); 
        
        %% set the speaker volume
        uicontrol('style','text',...
            'units','character',...
            'position', [95 2 7 1],...
            'backgroundcolor',c,...
            'string','Volume'); 
        uicontrol('style','edit',...
            'units','character',...
            'position', [103 2 6 1.5],...
            'horizontalalignment','center',...
            'backgroundcolor',c,...
            'string',snd.volume,...
            'tag','volume',...
            'callback','set_rec'); 
        
        
        if snd.runmode==1    %%  if TDT hardware is connected plot waveform        
	
%             ha1=axes('units','character','position', [50 10 50 14],'tag','waveform','nextplot','replacechildren');
            ha1=axes('units','character','position', [50 10 50 14],'tag','waveform','nextplot','add');
            set(gca,'YLimmode','manual','YLim',[-5 5]);
            xlabel('sampling points');
            ylabel('amplitude (V)');
%             lh1=line;
	
            uicontrol('style','pushbutton',...
                'units','character',...
                'position', [42 21 4 2],...
                'horizontalalignment','center',...
                'string','>',...
                'callback','set(gca,''YLim'',(get(gca,''Ylim'')*2))'); 
            uicontrol('style','pushbutton',...
                'units','character',...
                'position', [42 10 4 2],...
                'horizontalalignment','center',...
                'string','<',...
                'callback','set(gca,''YLim'',(get(gca,''Ylim'')/2))'); 
            plotpoints=1000;
            rec.dispwave=1;
            h=findobj(0,'tag','set_ch_params_win');
            figure(h);
        
            fullwave_max=0;
            fullwave_min=0;
            
            while rec.dispwave==1
                drawnow;
                invoke(RA_16,'SoftTrg',2);
                iii=invoke(RA_16,'gettagval','Oscindex');
                
                while iii<plotpoints
                    iii=invoke(RA_16,'gettagval','Oscindex');
                    drawnow;
                end
                
                fullwave=invoke(RA_16,'readtagv','OscData',0,plotpoints);
                temp_min=min(fullwave);
                temp_max=max(fullwave);
                
                if temp_min<fullwave_min
                    fullwave_min=temp_min;
                end
                if temp_max>fullwave_max
                    fullwave_max=temp_max;
                end
                switch rec.OscCh
                    case 1
                        curr_thresh=rec.thresh1;
                    case 2
                        curr_thresh=rec.thresh2;
                    case 3
                        curr_thresh=rec.thresh3;
                    case 4
                        curr_thresh=rec.thresh4;
                end
                    
                
                
                
                
                    
                if gcf==h
%                     set(lh1,'xdata',[1:length(fullwave)],'ydata',fullwave);  %draws the continuous waveform
                    y_range=get(gca,'YLim');

                    plot(fullwave,'k');
                    set(gca,'nextplot','add')
                    plot(get(gca,'xlim'),[fullwave_min,fullwave_min;fullwave_max,fullwave_max;curr_thresh,curr_thresh]');
                    set(gca,'nextplot','replace','ylim',y_range)
                    
                  else;
                    break
                end;
                drawnow;
            end
        end
    end
return;