function doOwland()
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

global snd rec screen_offset

%%colors (try tinkering with them when procrastinating)
c_yellow=[.95, .95, .7];
c_green=[.5,.58,.5];
c_red=[.7 .4 .4];
c_line=[.3 .3 .3];

myscreen=get(0, 'Screensize');   %%size of Screen for opening windows

%%open the windows
figure('position',[screen_offset+4  ((2-snd.controlwindow)*30+4) ((myscreen(3)/2)-8) ((myscreen(4)/3)-48)],...
    'menubar','none',...
    'color',c_green ,...
    'tag','Aud_Space_win');


figure('position',[((myscreen(3)/2)+screen_offset+4)  ((2-snd.controlwindow)*30+4) ((myscreen(3)/2)-8) ((myscreen(4)/3)-48)],...
    'menubar','none',...
    'color', c_green,...
    'tag','disp_win_3');


figure('position',[screen_offset+4 (myscreen(4)/3+12) ((myscreen(3)/2)-8) (2*myscreen(4)/3-90)],...
    'color', c_yellow,...
    'tag','disp_win_1');
fa = uimenu('Label','background');
uimenu(fa,'Label','Black','Callback','set(gcf,''color'',[0,0,0])');
uimenu(fa,'Label','White','Callback','set(gcf,''color'',[1,1,1])');
uimenu(fa,'Label','Cream','Callback','set(gcf,''color'',[.95, .95, .7])');
uimenu(fa,'Label','Green','Callback','set(gcf,''color'',[.4,.6,.4])');
uimenu(fa,'Label','Burgundy','Callback','set(gcf,''color'',[.6 .2 .2])');
uimenu(fa,'Label','');
uimenu(fa,'Label','Other','Callback','set_color');



figure('position',[((myscreen(3)/2)+screen_offset+4) (myscreen(4)/3+12) ((myscreen(3)/2)-8) (2*myscreen(4)/3-90)],...
    'color', c_yellow,...
    'tag','disp_win_2');
fa = uimenu('Label','background');
uimenu(fa,'Label','Black','Callback','set(gcf,''color'',[0,0,0])');
uimenu(fa,'Label','White','Callback','set(gcf,''color'',[1,1,1])');
uimenu(fa,'Label','Cream','Callback','set(gcf,''color'',[.95, .95, .7])');
uimenu(fa,'Label','Green','Callback','set(gcf,''color'',[.4,.6,.4])');
uimenu(fa,'Label','Burgundy','Callback','set(gcf,''color'',[.6 .2 .2])');
uimenu(fa,'Label','');
uimenu(fa,'Label','Other','Callback','set_color');


figure(findobj(0,'tag','Aud_Space_win'));     %% set the control window as active

%%set the menus
fa = uimenu('Label','File');
uimenu(fa,'Label','Open File','Callback','open_file',...
    'Separator','off','Accelerator','O');
uimenu(fa,'Label','Save File','Callback','save_file_dialog',...
    'Separator','off','Accelerator','S');
uimenu(fa,'Label','Update File','Callback','update_file',...
    'Separator','off','Accelerator','U');
uimenu(fa,'Label','');
uimenu(fa,'Label','Next','Callback','next_trace;',...
    'Accelerator','F');
uimenu(fa,'Label','Previous','Callback','prev_trace;',...
    'Separator','on','Accelerator','B');
uimenu(fa,'Label','');
uimenu(fa,'Label','Quit','Callback','close_AS;',...
    'Separator','on','Accelerator','Q');
fb = uimenu('Label','Test');
uimenu(fb,'Label','Run Test','Callback','run_tuning_curve_cb',...
    'Separator','on','Accelerator','R');
uimenu(fb,'Label','');
uimenu(fb,'Label','Collect Spike training','Callback','collect_spike_training_AS','Separator','on');
uimenu(fb,'Label','Run Continuous','Callback','set_continuous','Accelerator','C');
uimenu(fb,'Label','');
uimenu(fb,'Label','Interleave Traces', 'Callback', 'interleave_cb');
uimenu(fb,'Label','');
uimenu(fb,'Label','Noise-tone blocks', 'Callback', 'doNoiseTone');
uimenu(fb,'Label','');
uimenu(fb,'Label','Pause','Callback','pause_cb;',...
    'Separator','off','Accelerator','P','tag','Pause_menu');
uimenu(fb,'Label','Stop','Callback','stop_cb;',...
    'Separator','on','Accelerator','K');


fc = uimenu('Label','Other');
uimenu(fc,'Label','Other params','Callback','other_params');
uimenu(fc,'Label','');
uimenu(fc,'Label','Save Default Copy','Callback','save_defaults');
uimenu(fc,'Label','');
uimenu(fc,'Label','Message','Callback','set_message','Accelerator','M');
uimenu(fc,'Label','');
%     uimenu(fc,'Label','Stimulus Grid','Callback','show_stim_grid','Accelerator','G');  % not working, take out
%     uimenu(fc,'Label','');
uimenu(fc,'Label','Estimate time','Callback','estimate_time');


uicontrol('style','text','units','normalized','position', [.00 .25 .75 .5],'backgroundcolor',c_yellow);%%line

uicontrol('style','text','units','normalized','position', [.00 .75 .98 .01],'backgroundcolor',c_line);%%line
uicontrol('style','text','units','normalized','position', [.0 .25 .98 .01],'backgroundcolor',c_line);%%line
uicontrol('style','text','units','normalized','position', [.75 .01 .006 .98],'backgroundcolor',c_line);%%line


%%   set Variable #1 range   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
d=.1;

uicontrol('style','text',...
    'units','normalized',...
    'position', [.2 .51+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Minimum',...
    'horizontalalignment','left');
uicontrol('style','text',...
    'units','normalized',...
    'position', [.3 .51+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Maximum',...
    'horizontalalignment','left');
uicontrol('style','text',...
    'units','normalized',...
    'position', [.4 .51+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Step',...
    'horizontalalignment','left');


uicontrol('style','popup',...
    'units','normalized',...
    'position', [.05 .45+d .15 .06],...
    'backgroundcolor', c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var1_choices,...
    'tag','Var1',...
    'callback','set_test_params;');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.2 .45+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var1min,...
    'tag','Var1min',...
    'callback','set_range_params;');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.3 .45+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var1max,...
    'tag','Var1max',...
    'callback','set_range_params;');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.4 .45+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var1step,...
    'tag','Var1step',...
    'callback','set_range_params;');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%%   set Variable #2 range   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('style','text',...
    'units','normalized',...
    'position', [.2 .375+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Minimum',...
    'tag','Var2_min_label',...
    'horizontalalignment','left');
uicontrol('style','text',...
    'units','normalized',...
    'position', [.3 .375+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Maximum',...
    'tag','Var2_max_label',...
    'horizontalalignment','left');
uicontrol('style','text',...
    'units','normalized',...
    'position', [.4 .375+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Step',...
    'tag','Var2_step_label',...
    'horizontalalignment','left');


uicontrol('style','popup',...
    'units','normalized',...
    'position', [.05 .315+d .15 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var2_choices,...
    'tag','Var2',...
    'value',7,...
    'callback','set_test_params;');


uicontrol('style','edit',...
    'units','normalized',...
    'position', [.2 .315+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var2min,...
    'tag','Var2min',...
    'callback','set_range_params;');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.3 .315+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var2max,...
    'tag','Var2max',...
    'callback','set_range_params;');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.4 .315+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.Var2step,...
    'tag','Var2step',...
    'callback','set_range_params;');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




uicontrol('style','text',...
    'units','normalized',...
    'position', [.52 .44+d .1 .05],...
    'backgroundcolor',c_yellow,...
    'string','Reps',...
    'horizontalalignment','left');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.52 .36+d .08 .06],...
    'backgroundcolor',c_yellow,...
    'horizontalalignment','left',...
    'string',snd.reps,...
    'tag','reps',...
    'callback','set_range_params;');


uicontrol('style','text',...
    'units','normalized',...
    'backgroundcolor',c_green,...
    'fontweight','bold',...
    'string', 'sound on',...
    'position', [.78 .515+d .2 .1],...
    'tag','sound_on');
uicontrol('style','checkbox',...
    'units','normalized',...
    'backgroundcolor',c_green,...
    'string', 'Save Sound',...
    'position', [.78 .415+d .2 .05],...
    'tag','save_sound',...
    'callback','set_range_params',...
    'enable','on');
uicontrol('style','checkbox',...
    'units','normalized',...
    'backgroundcolor',c_green,...
    'string', 'Save Spikes',...
    'position', [.78 .315+d .2 .05],...
    'tag','save_spikes',...
    'callback','set_range_params',...
    'value',0,...
    'enable','on');
uicontrol('style','checkbox',...
    'units','normalized',...
    'backgroundcolor',c_green,...
    'string', 'Interleave Alone',...
    'position', [.78 .215+d .2 .05],...
    'tag','interleave_alone',...
    'callback','set_range_params',...
    'enable','off');






%%  interface buttons %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.03 .05 .12 .15],...
    'horizontalalignment','center',...
    'string','Stimulus',...
    'backgroundcolor', c_yellow,...
    'fontweight','bold',...
    'callback','setsnd');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.18 .05 .12 .15],...
    'horizontalalignment','center',...
    'string','Amplifier',...
    'fontweight','bold',...
    'tag','Amp_params',...
    'backgroundcolor', c_yellow,...
    'callback','set_AS_ch');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.32 .05 .12 .15],...
    'horizontalalignment','center',...
    'string','Visual Grid',...
    'tag','Vis_grid',...
    'backgroundcolor', c_yellow,...
    'fontweight','bold',...
    'callback','Vis_Field');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.46 .05 .12 .15],...
    'horizontalalignment','center',...
    'string','Map Field',...
    'fontweight','bold',...
    'backgroundcolor', c_yellow,...
    'tag','map_field_button',...
    'callback','map_field');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.60 .05 .12 .15],...
    'horizontalalignment','center',...
    'string','Auditory Search',...
    'fontweight','bold',...
    'backgroundcolor', c_yellow,...
    'tag','aud_search_button',...
    'callback','aud_pointnclick');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.8 .05 .15 .15],...
    'horizontalalignment','center',...
    'string','Run Test',...
    'backgroundcolor',c_red,...
    'fontweight','bold',...
    'tag','runtest',...
    'callback','run_tuning_curve_cb');


%%%display controls
%%  window to print the current rep into
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.05 .9 .3 .08],...
    'backgroundcolor',c_green,...
    'horizontalalignment','center',...
    'string',snd.filename,...
    'tag','filename');

uicontrol('style','edit',...
    'units','normalized',...
    'position', [.05 .8 .3 .08],...
    'backgroundcolor',c_green,...
    'horizontalalignment','left',...
    'tag','Print_rep');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.38 .9 .04 .08],...
    'horizontalalignment','center',...
    'string','<<',...
    'backgroundcolor', c_yellow,...
    'callback','first_trace');
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.42 .9 .03 .08],...
    'horizontalalignment','center',...
    'backgroundcolor', c_yellow,...
    'string','<',...
    'callback','prev_trace');

uicontrol('style','edit',...
    'units','normalized',...
    'position', [.45 .9 .2 .08],...
    'backgroundcolor',c_green,...
    'horizontalalignment','center',...
    'tag','Print_trace',...
    'callback','jump_to_trace');
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.65 .9 .03 .08],...
    'horizontalalignment','center',...
    'string','>',...
    'backgroundcolor', c_yellow,...
    'callback','next_trace');
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.68 .9 .04 .08],...
    'horizontalalignment','center',...
    'string','>>',...
    'backgroundcolor', c_yellow,...
    'callback','last_trace');



uicontrol('style','text',...
    'units','normalized',...
    'position', [.43 .8 .1 .06],...
    'backgroundcolor',c_green,...
    'string','Channel = ',...
    'horizontalalignment','left');

uicontrol('style','popupmenu',...
    'units','normalized',...
    'position', [.54 .8 .1 .08],...
    'backgroundcolor',c_green,...
    'horizontalalignment','left',...
    'string',num2cell([1:rec.numch]),...
    'tag','dispch',...
    'callback','set_dispch;');


%%%mask and unmask a pause button
uicontrol('style','text','units','normalized','position', [.8 .8 .15 .15],'backgroundcolor',c_line,'visible','on');
uicontrol('style','text','units','normalized','position', [.81 .81 .13 .13],'backgroundcolor',[0.8,0.5,0.0],'visible','on');

uicontrol('style','text','units','normalized','position', [.825 .825 .1 .1],'string','Pause',...
    'backgroundcolor',[0.8,0.5,0.0],'fontsize',12,'fontweight','bold','visible','on');

uicontrol('style','text','units','normalized','position', [.8 .8 .15 .15],'tag', 'pause_indicator',...
    'backgroundcolor',c_green,'visible','on');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if snd.runmode~=1
    set(findobj(gcf,'tag','map_field_button'),'enable','off');
    %         set(findobj(gcf,'tag','Vis_grid'),'enable','off');
    set(findobj(gcf,'tag','runtest'),'enable','off');
end


set_range_params;
set_test_params;
analysis_controls;
figure(findobj(0,'tag','Aud_Space_win'));     %% set the first window as active




end

