function interleave_cb()
global snd multsnd;
% GUI window for interleaving traces

clear global list multsnd 
global list multsnd screen_offset;


    c_yellow=[.95, .95, .7];
    c_green=[.5,.58,.5]; 
    c_red=[.7 .4 .4];
    
    if findobj(0,'tag','Interleave_win')>=1
        figure(findobj(0,'tag','Interleave_win'));     %% set the first window as active
      else   
        myscreen=get(0,'screensize');
        figure('position',[screen_offset+4,(myscreen(4)-430),400,400],'menubar','none','tag','Interleave_win', 'color', c_green);

         uicontrol('style','text',...
        'units','normalized',...
        'position', [.25 .84 .8 .1],...
        'backgroundcolor',c_green,...
        'string','Interleave Mult Traces ',...
        'fontweight','bold',...
        'fontsize',14,...
        'horizontalalignment','left');

        uicontrol('style','pushbutton',...
		'units','normalized',...
		'position', [.1 .72 .25 .1],...
		'horizontalalignment','center',...
		'string','Add to list',...
        'backgroundcolor',c_yellow,...
		'callback','add_inter_cb');
       
        uicontrol('style','pushbutton',...
		'units','normalized',...
		'position', [.4 .72 .25 .1],...
		'horizontalalignment','center',...
		'string','Remove from list',...
        'backgroundcolor',c_yellow,...
		'callback','remove_inter_cb');
    
        uicontrol('style','pushbutton',...
		'units','normalized',...
		'position', [.7 .72 .25 .1],...
		'horizontalalignment','center',...
		'string','Display params',...
        'backgroundcolor',c_yellow,...
		'callback','disp_inter_cb');

       uicontrol('style','Listbox',...
    	'units','normalized',...
    	'position', [.1 .125 .5 .5],...
    	'backgroundcolor',c_yellow,...
    	'horizontalalignment','left',...
  		'string','',...
   	    'tag','inter_tag'); 
    
        uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [.7 .15 .25 .15],...
        'horizontalalignment','center',...
        'string','Run Test',...
        'backgroundcolor',c_red,...
        'fontweight','bold',...
        'tag','run',...
        'callback','run_inter_tuning_curve_cb');
        
        uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [.7 .35 .25 .15],...
        'horizontalalignment','center',...
        'string','Close',...
        'backgroundcolor',c_red,...
        'fontweight','bold',...
        'tag','close',...
        'callback','close');
    
end

return