function other_params()
    global snd

    if findobj(0,'tag','other_params_win')>=1
        figure(findobj(0,'tag','other_params_win'));     %% set the first window as active
      else    %%open a new window
        myscreen=get(0,'screensize');
        figure('position',[4,(myscreen(4)-380),200,350],'menubar','none','tag','other_params_win');
	    c=get(gcf,'color');

        uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.05 .9 .9 .07],...
        	'backgroundcolor',c,...
        	'string','Other Parameters',...
        	'horizontalalignment','center',...
        	'fontweight','bold',...
        	'fontsize',14);

        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.1 .8 .4 .055],...
       	    'backgroundcolor',c,...
       	    'string','Blank Screen',...
       	    'horizontalalignment','left');
        uicontrol('style','popup',...
        	'units','normalized',...
        	'position', [.55 .8 .3 .055],...
        	'backgroundcolor',c,...
        	'horizontalalignment','left',...
      		'string',{'yes','no'},...
       	    'tag','screenblank',...
            'value',(2-snd.screenblank),...
        	'callback','set_other_params;');  
        
        
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.1 .7 .4 .055],...
       	    'backgroundcolor',c,...
       	    'string','Start Pause',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.55 .7 .3 .055],...
        	'backgroundcolor',c,...
        	'horizontalalignment','left',...
      		'string',snd.startpause,...
       	    'tag','startpause',...
        	'callback','set_other_params;'); 

        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.1 .6 .4 .055],...
       	    'backgroundcolor',c,...
       	    'string','Pause return',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.55 .6 .3 .055],...
        	'backgroundcolor',c,...
        	'horizontalalignment','left',...
      		'string',snd.pause_return,...
       	    'tag','pause_return',...
        	'callback','set_other_params;'); 
    end
return