function save_existing_raw_file_dialog()
    global snd rec;
    snd.oldname=snd.filename;
    
    screen=get(0,'screensize');
    figure('position',[screen(3)/2-200 screen(4)/2-100 400 200],...
        'windowstyle','modal',...
        'menubar','none')
    c=get(gcf,'color');

    uicontrol('style','text',...
        'units','normalized',...
        'backgroundcolor',c,...
        'position',[0.1 0.7 0.8 0.2],...
        'string','Warning: The filename you have selected already has a raw waveform!',...
        'fontsize',12,...
        'fontweight','bold',...
        'horizontalalignment','center');
    
    
    uicontrol('style','text',...
        'units','normalized',...
        'backgroundcolor',c,...
        'position',[0.1 0.45 0.8 0.2],...
        'string',strcat(snd.path,snd.filename,'_raw.mat'),...
        'horizontalalignment','center');

    uicontrol('style','text',...
        'units','normalized',...
        'backgroundcolor',c,...
        'position',[0.1 0.25 0.8 0.2],...
        'string','What would you like to do?',...
        'fontsize',10,...
        'fontweight','bold',...
        'horizontalalignment','center');
    
    
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position',[0.15 0.05 0.3 0.2],...
        'string','Overwrite file',...
        'fontweight','bold',...
        'callback','close(gcf);save_raw_file_bin_overwrite');   % <<<<<  km: add function to overwrite

    %%here is the new save button
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position',[0.55 0.05 0.3 0.2],...
        'string','Choose a new file',...
        'fontweight','bold',...
        'callback','close(gcf);save_raw_file_dialog');
  
return;
