function set_cont_segments()
    global cont
    figure('position',[400,300,400,150],'menubar','none');
    c=get(gcf,'color');

    
    uicontrol('style','checkbox',...
    	'units','normalized',...
    	'position', [.05 .7 .2 .1],...
    	'horizontalalignment','right',...
  		'string','Auditory',...
        'backgroundcolor',c,...
        'tag','aud','value',1);
    uicontrol('style','checkbox',...
    	'units','normalized',...
    	'position', [.25 .7 .2 .1],...
    	'horizontalalignment','right',...
  		'string','Visual',...
        'backgroundcolor',c,...
        'tag','vis','value',1);
    uicontrol('style','checkbox',...
    	'units','normalized',...
    	'position', [.45 .7 .2 .1],...
    	'horizontalalignment','right',...
  		'string','Bimodal',...
        'backgroundcolor',c,...
        'tag','bim','value',1);
    
    uicontrol('style','popup',...
    	'units','normalized',...
    	'position', [.7 .7 .25 .1],...
    	'backgroundcolor',c,...
    	'horizontalalignment','left',...
  		'string',{'right','left','both'},...
   	    'tag','pred_dir','value',3);  
    

    uicontrol('style','text',...
    	'units','normalized',...
    	'position', [.05 .4 .2 .1],...
    	'horizontalalignment','right',...
  		'string','Speed (deg/s) ',...
        'backgroundcolor',c);
    uicontrol('style','edit',...
    	'units','normalized',...
    	'position', [.25 .4 .1 .12],...
    	'horizontalalignment','left',...
  		'string','16',...
        'backgroundcolor',c,...
        'tag','speed');
    
    uicontrol('style','text',...
    	'units','normalized',...
    	'position', [.05 .25 .2 .1],...
    	'horizontalalignment','right',...
  		'string','size (deg) ',...
        'backgroundcolor',c);
    uicontrol('style','edit',...
    	'units','normalized',...
    	'position', [.25 .25 .1 .12],...
    	'horizontalalignment','left',...
  		'string','16',...
        'backgroundcolor',c,...
        'tag','size');
    
    uicontrol('style','text',...
    	'units','normalized',...
    	'position', [.5 .4 .1 .1],...
    	'horizontalalignment','center',...
  		'string','Min',...
        'backgroundcolor',c);
    uicontrol('style','text',...
    	'units','normalized',...
    	'position', [.65 .4 .1 .1],...
    	'horizontalalignment','center',...
  		'string','Max',...
        'backgroundcolor',c);
    uicontrol('style','text',...
    	'units','normalized',...
    	'position', [.8 .4 .1 .1],...
    	'horizontalalignment','center',...
  		'string','Step',...
        'backgroundcolor',c);
    uicontrol('style','edit',...
    	'units','normalized',...
    	'position', [.5 .25 .1 .12],...
    	'horizontalalignment','center',...
  		'string',cont.az_min,...
        'tag','min',...
        'backgroundcolor',c);
    uicontrol('style','edit',...
    	'units','normalized',...
    	'position', [.65 .25 .1 .12],...
    	'horizontalalignment','center',...
  		'string',cont.az_max,...
        'tag','max',...
        'backgroundcolor',c);
    uicontrol('style','edit',...
    	'units','normalized',...
    	'position', [.8 .25 .1 .12],...
    	'horizontalalignment','center',...
  		'string',(cont.az_max-cont.az_min)/10,...
        'tag','step',...
        'backgroundcolor',c);

    
    
    
    
     uicontrol('style','pushbutton',...
    	'units','normalized',...
    	'position', [.05 .05 .4 .1],...
        'fontweight','bold',...
    	'horizontalalignment','center',...
  		'string','Cancel',...
    	'callback','close;');     
    uicontrol('style','pushbutton',...
    	'units','normalized',...
    	'position', [.55 .05 .4 .1],...
        'fontweight','bold',...
    	'horizontalalignment','center',...
  		'string','Load',...
    	'callback','load_seg_curves;');     
