% function set_color
	    c=get(gcf,'color');
        myscreen=get(0,'screensize');
   figure('position',[myscreen(3)/2-50,myscreen(4)/2-50,100,100],...
        'menubar','none','color',c);
        
	uicontrol('style','slider',...
   	    'units','normalized',...
   	    'position', [.1 .1 .08 .8],...
        'min',0,'max',1,...
        'value',c(1),...
   	    'horizontalalignment','left',...
        'tag','red_val',...
        'callback','c(1)=get(findobj(gcf,''tag'',''red_val''),''value'');set(gcf,''color'',c)');
	uicontrol('style','slider',...
   	    'units','normalized',...
   	    'position', [.2 .1 .08 .8],...
        'min',0,'max',1,...
        'value',c(2),...
   	    'horizontalalignment','left',...
        'tag','green_val',...
        'callback','c(2)=get(findobj(gcf,''tag'',''green_val''),''value'');set(gcf,''color'',c)');
	uicontrol('style','slider',...
   	    'units','normalized',...
   	    'position', [.3 .1 .08 .8],...
        'min',0,'max',1,...
        'value',c(3),...
   	    'horizontalalignment','left',...
        'tag','blue_val',...
        'callback','c(3)=get(findobj(gcf,''tag'',''blue_val''),''value'');set(gcf,''color'',c)');
	uicontrol('style','pushbutton',...
   	    'units','normalized',...
   	    'position', [.5 .2 .4 .2],...
        'string','close',...
   	    'horizontalalignment','center',...
        'callback','close;set(gcf,''color'',c);c');
	uicontrol('style','pushbutton',...
   	    'units','normalized',...
   	    'position', [.5 .6 .4 .2],...
        'string','update',...
   	    'horizontalalignment','center',...
        'callback','close;set(gcf,''color'',c);set_color');

% return
