function set_AS_ch()
global RP_1 RP_2 pa5_1 pa5_2 RA_16  zbus vis rec snd screen_offset;
%This controls the amplifier window


test_passed=invoke(RA_16,'GetTagVal','RA16eight_loaded'); %% Kluge to check that RA_16 is running correct rco file
if ~test_passed
    % Load correct RA_16
    invoke(RA_16,'halt');
    invoke(RA_16,'ClearCOF');
    currentdir=pwd;
    RPVDS_path=strcat(currentdir,'\..\RPVDS');
    if invoke(RA_16,'loadCOFsf',strcat(RPVDS_path,'\','RA16eight'), 2)
        'RA16eight loaded on RA16'
    else
        'error in loading RA16'
    end
    set_RA16;
end


if findobj(0,'tag','set_ch_params_win')>=1 %If the figure is already open
    figure(findobj(0,'tag','set_ch_params_win'));     %% set the first window as active
else    %%open a new window
    myscreen=get(0,'screensize');
    figure('position',[screen_offset+4,(myscreen(4)-430),725,400],...
        'menubar','none',...
        'tag','set_ch_params_win'); %Generate the figure; name it set_ch_params_win
    
    c=get(gcf,'color');
    uicontrol('style','text',...
        'units','character',...
        'position', [50 28 60 2],...
        'backgroundcolor',c,...
        'string','Set Channel Parameters',...
        'horizontalalignment','left',...
        'fontweight','bold',...
        'fontsize',14);
    
    %%  Number of channels to record from
    uicontrol('style','text',...
        'units','character',...
        'position', [8 29.5 30 1],...
        'backgroundcolor',c,...
        'string','Number of Channels',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 29.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.numch,...
        'tag','numch',...
        'callback','set_rec');
    
    
    %% center of bandpass filter
    uicontrol('style','text',...
        'units','character',...
        'position', [8 27.5 30 1],...
        'backgroundcolor',c,...
        'string','Center of BP Filter',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 27.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.filtcent,...
        'tag','filtcent',...
        'callback','set_rec');
    
    
    %% width of bandpass filter
    uicontrol('style','text',...
        'units','character',...
        'position', [8 26 30 1],...
        'backgroundcolor',c,...
        'string','Width of BP Filter',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 26 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.filtwidth,...
        'tag','filtwidth',...
        'callback','set_rec');
    
    %% Channel gain
    uicontrol('style','text',...
        'units','character',...
        'position', [8 24.5 30 1],...
        'backgroundcolor',c,...
        'string','Gain for Channels',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 24.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.gain,...
        'tag','gain',...
        'callback','set_rec');
    
    %% Channel shift
    uicontrol('style','text',...
        'units','character',...
        'position', [8 23 30 1],...
        'backgroundcolor',c,...
        'string','Shift for Channels',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 23 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.shift,...
        'tag','shift',...
        'callback','set_rec');
    
    
    
    %% Channel Identity
    uicontrol('style','text',...
        'units','character',...
        'position', [4 20 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID1',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 20 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID1,...
        'tag','Ch_ID1',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [4 18.5 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID2',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 18.5 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID2,...
        'tag','Ch_ID2',...
        'callback','set_rec');
    
    uicontrol('style','text',...
        'units','character',...
        'position', [4 17 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID3',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 17 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID3,...
        'tag','Ch_ID3',...
        'callback','set_rec');
    
    uicontrol('style','text',...
        'units','character',...
        'position', [4 15.5 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID4',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 15.5 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID4,...
        'tag','Ch_ID4',...
        'callback','set_rec');
    
    %%ADDED these 4 djt 9/13/2012
    %%Positions may be maddd off
    uicontrol('style','text',...
        'units','character',...
        'position', [4 14 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID5',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 14 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID5,...
        'tag','Ch_ID5',...
        'callback','set_rec');
    
    uicontrol('style','text',...
        'units','character',...
        'position', [4 12.5 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID6',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 12.5 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID6,...
        'tag','Ch_ID6',...
        'callback','set_rec');
    
    uicontrol('style','text',...
        'units','character',...
        'position', [4 11 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID7',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 11 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID7,...
        'tag','Ch_ID7',...
        'callback','set_rec');
    
    uicontrol('style','text',...
        'units','character',...
        'position', [4 9.5 8 1],...
        'backgroundcolor',c,...
        'string','Ch ID8',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [12 9.5 6 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.ChID8,...
        'tag','Ch_ID8',...
        'callback','set_rec');
    
    %%%%HOLY SHIT FOUND THE PROBLEM GOING TO FIX THIS LATER THATS AWSEOM!!!
    
    
    
    %% Channel Thresholds
    uicontrol('style','text',...
        'units','character',...
        'position', [20 20 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 20 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh1,...
        'tag','thresh1',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [20 18.5 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 18.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh2,...
        'tag','thresh2',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [20 17 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 17 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh3,...
        'tag','thresh3',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [20 15.5 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 15.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh4,...
        'tag','thresh4',...
        'callback','set_rec');
    %%Added 4 more channels djt 9/13/2012
    %%positions may be madd off
    uicontrol('style','text',...
        'units','character',...
        'position', [20 14 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 14 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh5,...
        'tag','thresh5',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [20 12.5 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 12.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh6,...
        'tag','thresh6',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [20 11 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 11 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh7,...
        'tag','thresh7',...
        'callback','set_rec');
    uicontrol('style','text',...
        'units','character',...
        'position', [20 9.5 10 1],...
        'backgroundcolor',c,...
        'string','Thresh',...
        'horizontalalignment','left');
    uicontrol('style','edit',...
        'units','character',...
        'position', [30 9.5 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',rec.thresh8,...
        'tag','thresh8',...
        'callback','set_rec');
    
    
    %%  Channel for Oscilloscope
    uicontrol('style','text',...
        'units','character',...
        'position', [8 6 30 1],...
        'backgroundcolor',c,...
        'string','Osc Channel',...
        'horizontalalignment','left');
    uicontrol('style','popupmenu',...
        'units','character',...
        'position', [30 6 10 1.5],...
        'backgroundcolor',c,...
        'horizontalalignment','left',...
        'string',num2cell([1:rec.numch]),...
        'tag','OscCh',...
        'callback','set_rec');
    
    
    % % % %         uicontrol('style','popupmenu',...
    % % % %         'units','normalized',...
    % % % %         'position', [.43 .85 .06 .1],...
    % % % %         'backgroundcolor',c,...
    % % % %         'horizontalalignment','left',...
    % % % %         'string',num2cell([1:rec.numch]),...
    % % % %         'tag','dispch',...
    % % % %         'callback','set_disp_params;');
    
    
    %%  Get the default Values;
    uicontrol('style','pushbutton',...
        'units','character',...
        'position', [15 2 15 2],...
        'horizontalalignment','center',...
        'string','Default Values',...
        'callback','get_rec_defaults');
    
    uicontrol('style','pushbutton',...
        'units','character',...
        'position', [35 2 15 2],...
        'horizontalalignment','center',...
        'string','Close',...
        'callback','close_rec');
    
    uicontrol('style','pushbutton',...
        'units','character',...
        'position', [55 2 15 2],...
        'horizontalalignment','center',...
        'string','Set Thresh',...
        'callback','set_thresh');
    uicontrol('style','pushbutton',...
        'units','character',...
        'position', [75 2 15 2],...
        'horizontalalignment','center',...
        'string','Amp off',...
        'callback','amp_off');
    
    
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [.9 .95 .1 .051],...
        'horizontalalignment','center',...
        'string','Refresh',...
        'callback','close;set_AS_ch;');
    
    %% set the speaker volume
    uicontrol('style','text',...
        'units','character',...
        'position', [95 2 7 1],...
        'backgroundcolor',c,...
        'string','Volume');
    uicontrol('style','edit',...
        'units','character',...
        'position', [103 2 6 1.5],...
        'horizontalalignment','center',...
        'backgroundcolor',c,...
        'string',snd.volume,...
        'tag','volume',...
        'callback','set_rec');
    
    %% snd.runmode=0 THIS guy stops window from coming up.  So its
    %% generated in here somewhere
    if snd.runmode==1    %%  if TDT hardware is connected plot waveform
        
        %            '1'
        %            keyboard
        %             ha1=axes('units','character','position', [50 10 50 14],'tag','waveform','nextplot','replacechildren');
        % subplot (1,2,1)
        ha1=axes('units','character','position', [50 7 100 20],'tag','waveform','nextplot','add'); %Make the window
        set(gca,'YLimmode','manual','YLim',[-5 5]);
        xlabel('sampling points');
        ylabel('amplitude (V)');
        
        %             ha2=axes('units','character','position', [75 10 20 14],'tag','waveform','nextplot','add'); %Make the window
        %             set(gca,'YLimmode','manual','YLim',[-5 5]);
        %             xlabel('sampling points');
        %             ylabel('amplitude (V)');
        %             lh1=line;
        
        
        %             '2'
        %             keyboard
        
        
        uicontrol('style','pushbutton',...
            'units','character',...
            'position', [42 21 4 2],...
            'horizontalalignment','center',...
            'string','>',...
            'callback','set(gca,''YLim'',(get(gca,''Ylim'')*2))');
        uicontrol('style','pushbutton',...
            'units','character',...
            'position', [42 10 4 2],...
            'horizontalalignment','center',...
            'string','<',...
            'callback','set(gca,''YLim'',(get(gca,''Ylim'')/2))');
        
        
        plotpoints=1000;
        rec.dispwave=1;
        h=findobj(0,'tag','set_ch_params_win');
        figure(h);
        
        
        fullwave_max=0;
        fullwave_min=0;
        
        %%Set overlay DJT 12/11/2012
        %This controls how many waves are overlayed
        uicontrol('style','text',...
            'units','character',...
            'position', [111 2 7 1],...
            'backgroundcolor',c,...
            'string','Overlay');
        uicontrol('style','edit',...
            'units','character',...
            'position', [119 2 6 1.5],...
            'horizontalalignment','center',...
            'backgroundcolor',c,...
            'string',rec.overlay,...
            'tag','overlay',...
            'callback','set_rec');
        
        
        wavematrix=zeros(rec.overlay,(31*20+1)); %initiate matrix for recieving 10 waves
        %31+1 = 32 (number of points per wave) and *20=amount I've
        %stretched each wave
        wavecounter=1;
        wavevector=zeros(1,32);
        checkoverlay=rec.overlay;
        
        %             '3'
        %             keyboard
        while rec.dispwave==1
            if rec.overlay~=checkoverlay
                wavematrix=zeros(rec.overlay,(31*20+1));
                checkoverlay=rec.overlay
            end
            drawnow;
            invoke(RA_16,'SoftTrg',2); %Hit trigger to reset OscIndex
            iii=invoke(RA_16,'gettagval','Oscindex');
            while iii<plotpoints %wait for buffer to fill with alotted number of points
                iii=invoke(RA_16,'gettagval','Oscindex');
                drawnow;
            end
            
            fullwave=invoke(RA_16,'readtagv','OscData',0,plotpoints); %Then grab the full wave
            
            OsWavInd=double(invoke(RA_16,'gettagval','OscWaveIndex'));
            %retrieve thresholded wave points since last cycle
            NumWaves=OsWavInd/32; %calculate how many waves this is
            
            if NumWaves>0; %if there were threshold crossings
                threshwave=invoke(RA_16,'readtagv','OscWave',0,OsWavInd);
                %                     %Then grab the full wave
                for nWave=1:NumWaves %filter it and plop it in the matrx
                    wavevector=threshwave(32*(nWave-1)+1:(32*nWave));
                    wavematrix(wavecounter,:)=WaveStretcher(wavevector);
                    if wavecounter>rec.overlay-1
                        wavecounter=1;
                    else
                        wavecounter=wavecounter+1;
                    end
                end
            end
            
            temp_min=min(fullwave);
            temp_max=max(fullwave);
            
            if temp_min<fullwave_min
                fullwave_min=temp_min;
            end
            if temp_max>fullwave_max
                fullwave_max=temp_max;
            end
            
            switch rec.OscCh
                case 1
                    curr_thresh=rec.thresh1;
                case 2
                    curr_thresh=rec.thresh2;
                case 3
                    curr_thresh=rec.thresh3;
                case 4
                    curr_thresh=rec.thresh4;
                    
                    %%added djt 9/13/2012
                case 5
                    curr_thresh=rec.thresh5;
                case 6
                    curr_thresh=rec.thresh6;
                case 7
                    curr_thresh=rec.thresh7;
                case 8
                    curr_thresh=rec.thresh8;
            end
            
            %                 '6'
            %                 keyboard
            
            
            if gcf==h  %If figure h is the active figure
                %                     set(lh1,'xdata',[1:length(fullwave)],'ydata',fullwave);  %draws the continuous waveform
                
                
                y_range=get(gca,'YLim');
                
                
                plot(fullwave,'k'); %plot the wave
                set(gca,'nextplot','add') %not sure what this is doing
                
                plot(plotpoints+20+1:plotpoints+20+length(wavematrix),wavematrix);
                set(gca,'nextplot','add') %not sure what this is doing
                
                plot(get(gca,'xlim'),[fullwave_min,fullwave_min;fullwave_max,fullwave_max;curr_thresh,curr_thresh]');
                %I think above line puts horizontal lines across screen
                %for the min, max and threshold
                set(gca,'nextplot','replace','ylim',y_range) %not sure what this is doing
                
                
                
                
                %axes(ha2);  %make axes for threshwave active
                %    y_range=get(gca,'YLim');
                
                
                %    plot(threshwave,'k'); %plot the wave
                %    set(gca,'nextplot','add') %not sure what this is doing
                %    plot(get(gca,'xlim'),[threshwave_min,threshwave_min;threshwave_max,threshwave_max;curr_thresh,curr_thresh]');
                
                %    set(gca,'nextplot','replace','ylim',y_range) %not sure what this is doing
                %                     '7'
                %                     keyboard
                
                
            else;
                break
            end;
            drawnow;
        end
        
        
        
        
        
    end
end
return;