function show_timecourse()

    global snd rec;
        
    if strcmp(get(gcf,'tag'),'disp_win_3')
        % timecourse selections in main window. 
        timecourse_type=get(findobj(gcf,'tag','time_course'),'value');
    else
        % timecourse selections in timecourse display window. 
        timecourse_type=get(findobj(gcf,'tag','time_course_II'),'value')+4;
    end
    
    myscreen=get(0,'screensize');
    
    if timecourse_type<=4
        figure('position',[myscreen(3)/2+4,myscreen(4)/2-100,myscreen(3)/2,myscreen(4)/2+70]);
        axes('units','normalized','position', [.1 .3 .88 .6],'nextplot','add');
        c=get(gcf,'color');
        snd.timecourse_plot_num=0;
        snd.tc_handle=[];
        snd.tc_string={};
        

       time_course_options={'Standard','Var 1','Var 2'};
       uicontrol('style','popup',...
        	'units','normalized',...
        	'position', [.05 .16 .15 .04],...
        	'backgroundcolor',c,...
        	'horizontalalignment','left',...
      		'string',time_course_options,...
       	    'tag','time_course_II');

        uicontrol('style','pushbutton',...
        	'units','normalized',...
        	'position', [.05 .11 .15 .04],...
        	'backgroundcolor',c,...
        	'string','Add',...
        	'horizontalalignment','center','callback','show_timecourse;');
        
       uicontrol('style','pushbutton',...
       	    'units','normalized',...
           	'position', [.05, .06, .15, .04], ... 
           	'backgroundcolor',c,...
           	'string','Clear',...
       	    'horizontalalignment','center','callback','clear_TC');

		uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.25 .16 .15 .04],...
        	'backgroundcolor',c,...
        	'string','Time range',...
        	'horizontalalignment','center'); 
      
	    uicontrol('style','edit',...
           'units','normalized',...
           'position', [.4 .16 .1 .04],...
           'horizontalalignment','center',...
           'tag','time_start',...
           'string',-snd.pre,'callback','update_timecourse;');

        uicontrol('style','edit',...
           'units','normalized',...
           'position', [.51 .16 .1 .04],...
           'horizontalalignment','center',...
           'tag','time_end',...
           'string',snd.post,'callback','update_timecourse;');

       	uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.25 .11 .15 .04],...
        	'backgroundcolor',c,...
        	'string','Var1 range',...
        	'horizontalalignment','center'); 
      
	    uicontrol('style','edit',...
           'units','normalized',...
           'position', [.4 .11 .1 .04],...
           'horizontalalignment','center',...
           'tag','var1_min',...
           'string',min(snd.Var1array));

        uicontrol('style','edit',...
           'units','normalized',...
           'position', [.51 .11 .1 .04],...
           'horizontalalignment','center',...
           'tag','var1_max',...
           'string',max(snd.Var1array));
      
        uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.25 0.06 .15 .04],...
        	'backgroundcolor',c,...
        	'string','Var2 range',...
        	'horizontalalignment','center'); 
      
	    uicontrol('style','edit',...
           'units','normalized',...
           'position', [.4 .06 .1 .04],...
           'horizontalalignment','center',...
           'tag','var2_min',...
           'string',min(snd.Var2array));

        uicontrol('style','edit',...
           'units','normalized',...
           'position', [.51 .06 .1 .04],...
           'horizontalalignment','center',...
           'tag','var2_max',...
           'string',max(snd.Var2array));

       uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.25 .01 .15 .04],...
        	'backgroundcolor',c,...
        	'string','Bin size (ms)',...
        	'horizontalalignment','center'); 
      
	    uicontrol('style','edit',...
           'units','normalized',...
           'position', [.4 .01 .1 .04],...
           'horizontalalignment','center',...
           'tag','filt_n',...
           'string','1');
     
       uicontrol('style','pushbutton',...
    	'units','normalized',...
    	'position', [.65 .16 .1 .04],...
        'backgroundcolor',c,...
    	'horizontalalignment','center',...
  		'string','Remove',...
   	    'callback','remove_TC'); 
       uicontrol('style','pushbutton',...
    	'units','normalized',...
    	'position', [.75 .16 .1 .04],...
        'backgroundcolor',c,...
    	'horizontalalignment','center',...
  		'string','Show',...
   	    'callback','show_TC'); 
       uicontrol('style','pushbutton',...
    	'units','normalized',...
    	'position', [.85 .16 .1 .04],...
        'backgroundcolor',c,...
    	'horizontalalignment','center',...
  		'string','Normal',...
   	    'callback','set(get(gca,''children''),''LineWidth'',2);'); 
       uicontrol('style','Listbox',...
    	'units','normalized',...
    	'position', [.65 .01 .3 .15],...
        'backgroundcolor',c,...
    	'horizontalalignment','left',...
  		'string','',...
   	    'tag','TC_list'); 
    end
    
    
        time_start=str2num(get(findobj(gcf,'tag','time_start'),'string'));
        time_end=str2num(get(findobj(gcf,'tag','time_end'),'string'));
        var1_min=str2num(get(findobj(gcf,'tag','var1_min'),'string'));
        var1_max=str2num(get(findobj(gcf,'tag','var1_max'),'string'));
        var2_min=str2num(get(findobj(gcf,'tag','var2_min'),'string'));
        var2_max=str2num(get(findobj(gcf,'tag','var2_max'),'string'));
        filt_n=str2num(get(findobj(gcf,'tag','filt_n'),'string'));  % filter size
      
        time_array=[-snd.pre:filt_n:snd.post];
        mycolors={[0,0,0],[1,0,0.1],[0.1,0.8,0.2],[0.1,0.3,0.6],[0.2,0.8,0.8],[0.6,0,0.6]};  % 6 colors to cycle through with plots
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % timecourse_type key: 1=standard, 2=var1, 3=var2, 4=all ... 5=standard, 6=var1, 7=var2
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
        if ismember(timecourse_type,[1,4,5]) % display 'standard' timecourse
            
            % check number of conditions (number of possible var1/var2 combinations)
            if snd.Var2~=7  %%there are two variables ranging
                    spikes = find(snd.datachan==rec.dispch & snd.datatime>=time_start & snd.datatime<=time_end & ...
                        snd.dataVar1>=var1_min & snd.dataVar1<=var1_max & snd.dataVar2>=var2_min & snd.dataVar2<=var2_max);
                    num_bins = length(find(snd.Var1array<=var1_max & snd.Var1array>=var1_min))* ...
                        length(find(snd.Var2array<=var2_max & snd.Var2array>=var2_min));   
             else
                    spikes = find(snd.datachan==rec.dispch & snd.datatime>=time_start & snd.datatime<=time_end & ...
                        snd.dataVar1>=var1_min & snd.dataVar1<=var1_max);
                    num_bins=length(find(snd.Var1array<=var1_max & snd.Var1array>=var1_min));   
            end
           
            
            tc=histc(snd.datatime(spikes),time_array);
            tc=1000*tc/(num_bins*snd.reps*filt_n);  
            
            color_number = 1 + mod(snd.timecourse_plot_num,6);  % cycle through color #s 1-6                     
            snd.timecourse_plot_num = snd.timecourse_plot_num+1;   % update for next plot's color            
            snd.tc_handle(snd.timecourse_plot_num)=plot(time_array,tc,'color',mycolors{color_number},'LineWidth', 2);
            snd.tc_string{snd.timecourse_plot_num}='Standard';

            set(gca,'XLimMode','manual','XLim',[time_start,time_end]);
            xlabel('time (ms)');
            ylabel('Rate (spikes/sec)');
            title(['Channel ',num2str(rec.dispch),'  Trace ',num2str(snd.trace)]);
        end   
        
        if ismember(timecourse_type,[2,4,6]) % display 'var1' timecourse
            spikes = find(snd.datachan_arr1==rec.dispch & snd.datatime_arr1>=time_start & ... 
            snd.datatime_arr1<=time_end & snd.dataVar1_arr1>=var1_min & snd.dataVar1_arr1<=var1_max);            
            num_bins=length(find(snd.Var1array<=var1_max & snd.Var1array>=var1_min));           
            tc=histc(snd.datatime_arr1(spikes),time_array);
            
            tc=1000*tc/(num_bins*snd.reps*filt_n);

            color_number = 1 + mod(snd.timecourse_plot_num,6);  % cycle through color #s 1-6 
            snd.timecourse_plot_num = snd.timecourse_plot_num+1;   % update for next plot's color            
            snd.tc_handle(snd.timecourse_plot_num)=plot(time_array,tc,'color',mycolors{color_number},'LineWidth', 2);
            snd.tc_string{snd.timecourse_plot_num}='Var1';
            set(gca,'XLimMode','manual','XLim',[time_start,time_end]);
            xlabel('time (ms)');
            ylabel('Rate (spikes/sec)');
            title(['Channel ',num2str(rec.dispch),'  Trace ',num2str(snd.trace),'  ',char(snd.Var1_choices(snd.Var1)),' alone']);
        end
        
        if ismember(timecourse_type,[3,4,7]) % display 'var2' timecourse
            spikes = find(snd.datachan_arr2==rec.dispch & snd.datatime_arr2>=time_start & ... 
                snd.datatime_arr2<=time_end & snd.dataVar2_arr2>=var2_min & snd.dataVar2_arr2<=var2_max);                        
            num_bins=length(find(snd.Var2array<=var2_max & snd.Var2array>=var2_min)); 
            tc=histc(snd.datatime_arr2(spikes),time_array);
             
            tc=1000*tc/(num_bins*snd.reps*filt_n);
          
            color_number = 1 + mod(snd.timecourse_plot_num,6);  % cycle through color #s 1-6 
            snd.timecourse_plot_num = snd.timecourse_plot_num+1;   % update for next plot's color            
            snd.tc_handle(snd.timecourse_plot_num)=plot(time_array,tc,'color',mycolors{color_number},'LineWidth', 2);
            snd.tc_string{snd.timecourse_plot_num}='Var2';
            set(gca,'XLimMode','manual','XLim',[time_start,time_end]);
            xlabel('time (ms)');
            ylabel('Rate (spikes/sec)');
            title(['Channel ',num2str(rec.dispch),'  Trace ',num2str(snd.trace),'  ',char(snd.Var2_choices(snd.Var2)),' alone']);
        end
    set( findobj('tag','TC_list'),'string', snd.tc_string );
return;
