function set_WA_map()
global snd 
global screen_offset chan_select fs maxlag full_var full_time wa_map_trace

c_yellow=[.95, .95, .7];
c_green=[.5,.58,.5];
c_red=[.7 .4 .4];

%set initial values
num_chan=max(snd.datachan);
chan_select = zeros(1,num_chan);
fs=1;
maxlag=20;
full_var=0;
full_time=0;
snd.ba_cutoff=50;
wa_map_trace=snd.trace;

%%open a new window
myscreen=get(0,'screensize');
figure('position',[(myscreen(3)/2+screen_offset),(myscreen(4)/2-380),300,600],'menubar','none','tag','doug_chanwin', 'color', c_yellow);

%% Channel Selection
for i=1:num_chan;
    uicontrol('style','text',...
        'units','normalized',...
        'position', [.05 .8/num_chan*(num_chan+1-i)+.08 .4 .1],...
        'backgroundcolor',c_yellow,...
        'string',strcat('Channel ', num2str(i)),...
        'horizontalalignment','center',...
        'fontsize',12);
    
    uicontrol('style','checkbox',...
        'units','normalized',...
        'position', [.4 .8/num_chan*(num_chan+1-i)+.14 .1 .05],...
        'backgroundcolor',c_yellow,...
        'fontsize',8,...
        'tag', strcat('chan',num2str(i)),...
        'callback', 'Update_Channels',...
        'horizontalalignment','left');
end

%% Select Buttons
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.6 .9 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Select All',...
    'fontsize',12,...
    'tag', 'select_all',...
    'callback', 'Update_Select_All',...
    'horizontalalignment','left');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.6 .85 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Deselect All',...
    'fontsize',12,...
    'tag', 'deselect_all',...
    'callback', 'Update_Deselect_All',...
    'horizontalalignment','left');

%% Control Settings
% %Bin Width
% uicontrol('style','text',...
%     'units','normalized',...
%     'position', [.55 .33 .4 .05],...
%     'backgroundcolor',c_yellow,...
%     'string','Bin Width (ms)',...
%     'fontsize',12,...
%     'fontweight','bold',...
%     'callback', 'Update_Set_EucDistance',...
%     'horizontalalignment','center');
% uicontrol('style','edit',...
%     'units','normalized',...
%     'position', [.65 .3 .2 .05],...
%     'backgroundcolor',c_yellow,...
%     'string',fs,...
%     'fontsize',12,...
%     'tag', 'freq',...
%     'callback', 'Update_Set_EucDistance',...
%     'horizontalalignment','center');

% % % %Select Trace
% % % uicontrol('style','text',...
% % %     'units','normalized',...
% % %     'position', [.6 .40 .15 .05],...
% % %     'backgroundcolor',c_yellow,...
% % %     'FontWeight','bold',...
% % %     'string','Select Trace',...
% % %     'tag','vis_offset2text',...
% % %     'horizontalalignment','left');
% % % uicontrol('style','edit',...
% % %     'units','normalized',...
% % %     'position', [.75 .40 .1 .05],...
% % %     'backgroundcolor',c_yellow,...
% % %     'horizontalalignment','left',...
% % %     'string',wa_map_trace,...
% % %     'tag','trace',...
% % %     'callback','Update_Set_WA_map;');

%Cutoff for Defining Peak
uicontrol('style','text',...
    'units','normalized',...
    'position', [.55 .23 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Cutoff (%)',...
    'fontsize',12,...
    'fontweight','bold',...
    'callback', 'Update_Set_WA_map',...
    'horizontalalignment','center');
uicontrol('style','edit',...
    'units','normalized',...
    'position', [.65 .2 .2 .05],...
    'backgroundcolor',c_yellow,...
    'string',snd.ba_cutoff,...
    'fontsize',12,...
    'tag', 'mlag',...
    'callback', 'Update_Set_WA_map',...
    'horizontalalignment','center');
% 
% %Choose Analyses
% uicontrol('style','checkbox',...
%     'units','normalized',...
%     'position', [.55 .5 .4 .05],...
%     'backgroundcolor',c_yellow,...
%     'fontsize',8,...
%     'string','Peak W-Ave',...
%     'tag', 'wap_on',...
%     'callback', 'Update_Set_EucDistance',...
%     'horizontalalignment','left');

% uicontrol('style','checkbox',...
%     'units','normalized',...
%     'position', [.55 .45 .4 .05],...
%     'backgroundcolor',c_yellow,...
%     'fontsize',8,...
%     'string','Global W-Ave',...
%     'tag', 'wag_on',...
%     'callback', 'Update_Set_EucDistance',...
%     'horizontalalignment','left');


%% Run Button
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.1 .025 .8 .1],...
    'horizontalalignment','center',...
    'string','Do it!',...
    'fontweight', 'bold', ...
    'fontsize', 10,...
    'backgroundcolor', c_red,...
    'callback','WA_Map_Wrap');
