function set_flex()
    global snd screen_offset spacemap pos_plots wa_plots;
    
    %Design the experiment for flexible stimulation
    %Hacked from setsnd by DJT 10/1/2013
    
    c_yellow=[.95, .95, .7];
    c_green=[.5,.58,.5]; 
    c_red=[.7 .4 .4];
    
    wa_plots=[];
    snd.flex_pos1=[-10,0];
    snd.flex_pos2=[20,0];
    snd.size_change_v2=0;
    snd.flex_v1_on=0;
    snd.flex_v2_on=0;
    snd.flex_a1_on=0;
    

        myscreen=get(0,'screensize');
        spacemap=figure('position',[4+screen_offset,(myscreen(4)-830),800,800],'menubar','none','tag','doug_flexwin', 'color', c_yellow); 
        %figure('position',[4,(myscreen(4)-380),800,350],'menubar','none','tag','JoeSound_win', 'color', c_yellow); %
        %Changed to reposition for extended display DJT 1/25/2012

		uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.05 .95 .25 .03],...
        	'backgroundcolor',c_yellow,...
        	'string','General Parameters',...
        	'horizontalalignment','center',...
        	'fontweight','bold',...
        	'fontsize',12);

        %% set duration
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08 .9 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Duration',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16 .9 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.duration,...
       	    'tag','reps',...
        	'callback','set_range_params;'); 
        
        %% set number of reps
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.35 .9 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Reps',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.4 .9 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.reps,...
       	    'tag','duration',...
        	'callback','update_set_flex;'); 
	
        %% set pre and post time
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08 .865 .18 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Pre / Post',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16 .865 .06 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.pre,...
       	    'tag','pre',...
        	'callback','update_set_flex;'); 
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.22 .865 .06 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.post,...
       	    'tag','post',...
        	'callback','update_set_flex;'); 
	
        %% Set the ISI
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08 .83 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','ISI',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16 .83 .04 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.isi,...
       	    'tag','isi',...
        	'callback','update_set_flex;'); 
	    uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.05 .75 .25 .04],...
        	'backgroundcolor',c_yellow,...
        	'string','Sound Parameters',...
        	'horizontalalignment','center',...
        	'fontweight','bold',...
        	'fontsize',12);
        
                %% set background
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08 .80 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Background',...
       	    'tag','backgroundtext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16 .80 .04 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.background,...
       	    'tag','background',...
        	'callback','update_set_flex;'); 
	
        d=-.07;
        dd=-.05;
        
        %%%SND1 STUFF
        %% label snd1
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.09+d .72 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','SND 1',...
            'tag', 'SND1text',...
            'fontweight', 'bold',...
            'fontsize', 10,...
       	    'horizontalalignment','left');
        uicontrol('style','checkbox',...
       	    'units','normalized',...
       	    'position', [.185+dd .72 .15 .03],...
       	    'backgroundcolor',c_yellow,...
            'tag', 'soundonoff',...
            'fontsize',8,...
            'string', 'Play it',...
            'tag', 'flex_a1_on',...
            'value', snd.flex_a1_on,...
            'callback', 'update_set_flex',...
       	    'horizontalalignment','left');

        %% set itd1
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .685 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','ITD1',...
            'tag', 'ITDtext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .685 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.itd1,...
       	    'tag','itd1',...
        	'callback','update_set_flex;'); 
        
        %% set ild1
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .65 .15 .03],...
       	    'backgroundcolor',c_yellow,...
            'tag', 'ILDtext',...
       	    'string','ILD1',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .65 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.ild1,...
       	    'tag','ild1',...
        	'callback','update_set_flex;'); 
        
        %% set abi1
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .615 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','ABI1',...
            'tag', 'ABItext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .615 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.abi1,...
       	    'tag','abi1',...
        	'callback','update_set_flex;'); 
      	
        %% set Low Frequency 1
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .58 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Freq Lo',...
       	    'horizontalalignment','left',...
            'tag','lofreqtext');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .58 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.freqlo1,...
       	    'tag','freqlo1',...
        	'callback','update_set_flex;'); 
        
        %% set High Freq 1
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .545 .15 .03],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Freq Hi',...
       	    'horizontalalignment','left',...
            'tag','hifreqtext');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .545 .08 .03],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.freqhi1,...
       	    'tag','freqhi1',...
        	'callback','update_set_flex;'); 
	
%         %%SND2 STUFF
%         d2= .11;
%         dd2=.09;
%         
%         %% label snd2
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.09+d2 .44 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','SND 2',...
%             'tag', 'SND2text',...
%             'fontweight', 'bold',...
%             'fontsize', 10,...
%        	    'horizontalalignment','left');
%         uicontrol('style','checkbox',...
%        	    'units','normalized',...
%        	    'position', [.185+dd2 .44 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%             'fontsize',8,...
%             'string', 'Play it',...
%             'tag', 'play_sound2',...
%             'value', snd.play_sound2,...
%             'callback', 'update_set_flex',...
%        	    'horizontalalignment','left');
% 
%         %% set itd2
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d2 .37 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','ITD2',...
%             'tag', 'ITD2text',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.16+dd2 .37 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.itd2,...
%        	    'tag','itd2',...
%         	'callback','update_set_flex;'); 
%         
%         %% set ild2
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d2 .3 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%             'tag', 'ILD2text',...
%        	    'string','ILD2',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.16+dd2 .3 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.ild2,...
%        	    'tag','ild2',...
%         	'callback','update_set_flex;'); 
%         
%         %% set abi2
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d2 .23 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','ABI2',...
%             'tag', 'ABI2text',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.16+dd2 .23 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.abi2,...
%        	    'tag','abi2',...
%         	'callback','update_set_flex;'); 
% 	
%         %% set Low Frequency 2
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d2 .16 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Freq Lo',...
%        	    'horizontalalignment','left',...
%             'tag','lofreqtext2');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.16+dd2 .16 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.freqlo2,...
%        	    'tag','freqlo2',...
%         	'callback','update_set_flex;'); 
%         
%         %% set High Freq 2
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d2 .09 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Freq Hi',...
%        	    'horizontalalignment','left',...
%             'tag','hifreqtext2');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.16+dd2 .09 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.freqhi2,...
%        	    'tag','freqhi2',...
%         	'callback','update_set_flex;'); 
%         

        
%        %% set ITDflank
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.35 .23 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','ITDflank',...
%        	    'horizontalalignment','left',...
%             'tag','ITDflank_text');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.42 .23 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.ITDflank,...
%        	    'tag','ITDflank',...
%         	'callback','update_set_flex;');
%         
%         %% set aud_offset
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.35 .16 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Aud Offset',...
%        	    'horizontalalignment','left',...
%             'tag','aud_offset_text');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.42 .16 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.aud_offset,...
%        	    'tag','aud_offset',...
%         	'callback','update_set_flex;'); 
% 	
% 	
%         %% set rise time
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.35 .09 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Rise time',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.42 .09 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.rise,...
%        	    'tag','rise',...
%         	'callback','update_set_flex;'); 	
% 	
% 	    %% set corr
% 	    uicontrol('style','checkbox',...
%        	    'units','normalized',...
%        	    'position', [.35 .3 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%             'fontsize',8,...
%             'string', 'corr',...
%             'tag', 'corr',...
%             'value', snd.corr,...
%             'callback', 'update_set_flex',...
%        	    'horizontalalignment','left');
	

            
        %% VIS1 Controls %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .8/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','VIS 1',...
            'tag', 'VIS1text',...
            'fontweight', 'bold',...
            'fontsize', 10,...
       	    'horizontalalignment','left');
       uicontrol('style','checkbox',...
       	    'units','normalized',...
       	    'position', [.12+dd .8/2 .1 .05/2],...
       	    'backgroundcolor',c_yellow,...
            'fontsize',8,...
            'string', 'Play it',...
            'tag', 'flex_v1_on',...
            'value', snd.flex_v1_on,...
            'callback', 'update_set_flex',...
       	    'horizontalalignment','left');

%         v=.08;
		uicontrol('style','text',...
        	'units','normalized',...
        	'position', [.05 .86/2 .25 .08/2],...
        	'backgroundcolor',c_yellow,...
        	'string','Visual Parameters',...
        	'horizontalalignment','center',...
        	'fontweight','bold',...
        	'fontsize',12);          
            

	
        % set foreground
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .73/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Foreground',...
       	    'tag','foregroundtext',...           
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .74/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.foreground,...
       	    'tag','foreground',...
        	'callback','update_set_flex;'); 
        
        % set dotsize
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .66/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Dot Size',...
            'tag','dotsizetext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .66/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.dotsize,...
       	    'tag','dotsize',...
        	'callback','update_set_flex;'); 
	
        % set distance
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .59/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Distance',...
            'tag','distancetext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .59/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.distance,...
       	    'tag','distance',...
        	'callback','update_set_flex;');
	
        % set angle
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .52/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Angle',...
            'tag','angletext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .52/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.angle,...
       	    'tag','angle',...
        	'callback','update_set_flex;'); 
	
        % set az
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .45/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Azimuth',...
            'tag','aztext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .45/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.az,...
       	    'tag','az',...
        	'callback','update_set_flex;'); 
	
        % set el
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .38/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Elevation',...
            'tag','eltext',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .38/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.el,...
       	    'tag','el',...
        	'callback','update_set_flex;'); 
		   % set size change
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.08+d .31/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
            'tag','size_change_text',...
       	    'string','Size Change',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.16+dd .31/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.size_change,...
       	    'tag','size_change',...
        	'callback','update_set_flex;'); 
%         % set vis_offset
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d .23/2 .15 .05/2],...
%        	    'backgroundcolor',c_yellow,...
%             'tag','vis_offsettext',...
%        	    'string','Vis Offset',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.16+dd .23/2 .04 .05/2],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.vis_offset,...
%        	    'tag','vis_offset',...
%         	'callback','update_set_flex;'); 
        
%         %% set_interleaved_modulation
%                 uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.08+d .16/2 .15 .05/2],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Loom Inter',...
%             'tag', 'VIS1text',...
%        	    'horizontalalignment','left');
%        uicontrol('style','checkbox',...
%        	    'units','normalized',...
%        	    'position', [.16+dd .16/2 .1 .05/2],...
%        	    'backgroundcolor',c_yellow,...
%             'fontsize',8,...
%             'string', 'Play it',...
%             'tag', 'inter_loom',...
%             'value', snd.inter_loom,...
%             'callback', 'update_set_flex',...
%        	    'horizontalalignment','left');

%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.44+v .8 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','VIS 1',...
%             'tag', 'VIS1text',...
%             'fontweight', 'bold',...
%             'fontsize', 10,...
%        	    'horizontalalignment','left');
%        uicontrol('style','checkbox',...
%        	    'units','normalized',...
%        	    'position', [.52+v .8 .1 .05],...
%        	    'backgroundcolor',c_yellow,...
%             'fontsize',8,...
%             'string', 'Play it',...
%             'tag', 'play_vis1',...
%             'value', snd.play_vis1,...
%             'callback', 'update_set_flex',...
%        	    'horizontalalignment','left');

	
        %% VIS2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        q=.18;
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .8/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','VIS 2',...
            'tag', 'VIS2text',...
            'fontweight', 'bold',...
            'fontsize', 10,...
       	    'horizontalalignment','left');
       uicontrol('style','checkbox',...
       	    'units','normalized',...
       	    'position', [.28+dd .8/2 .1 .05/2],...
       	    'backgroundcolor',c_yellow,...
            'fontsize',8,...
            'string', 'Play it',...
            'tag', 'flex_v2_on',...
            'value', snd.flex_v2_on,...
            'callback', 'update_set_flex',...
       	    'horizontalalignment','left');
			
        % set foreground
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .73/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Foreground',...
            'tag','foreground2text',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.32+dd .73/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.foreground2,...
       	    'tag','foreground2',...
        	'callback','update_set_flex;'); 
        % set dotsize
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .66/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Dot Size',...
            'tag','dotsize2text',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.32+dd .66/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.dotsize2,...
       	    'tag','dotsize2',...
        	'callback','update_set_flex;'); 
	
        % set distance
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .59/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Distance',...
            'tag','distance2text',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.32+dd .59/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.distance2,...
       	    'tag','distance2',...
        	'callback','update_set_flex;'); 
	
        % set angle
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .52/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Angle',...
            'tag','angle2text',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.32+dd .52/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.angle2,...
       	    'tag','angle2',...
        	'callback','update_set_flex;'); 
	
        % set az
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .45/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Azimuth',...
            'tag','az2text',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.32+dd .45/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.az2,...
       	    'tag','az2',...
        	'callback','update_set_flex;'); 
	
        % set el
        uicontrol('style','text',...
       	    'units','normalized',...
       	    'position', [.24+d .38/2 .15 .05/2],...
       	    'backgroundcolor',c_yellow,...
       	    'string','Elevation',...
            'tag','el2text',...
       	    'horizontalalignment','left');
        uicontrol('style','edit',...
        	'units','normalized',...
        	'position', [.32+dd .38/2 .04 .05/2],...
        	'backgroundcolor',c_yellow,...
        	'horizontalalignment','left',...
      		'string',snd.el2,...
       	    'tag','el2',...
        	'callback','update_set_flex;'); 
        
        % set size change
        uicontrol('style','text',...
            'units','normalized',...
            'position', [.24+d .31/2 .15 .05/2],...
            'backgroundcolor',c_yellow,...
            'tag','size_change_v2_text',...
            'string','Size Change',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','normalized',...
            'position', [.32+dd .31/2 .04 .05/2],...
            'backgroundcolor',c_yellow,...
            'horizontalalignment','left',...
            'string',snd.size_change_v2,...
            'tag','size_change_v2',...
            'callback','update_set_flex;');
	
%         % set vis_offset
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.24+d .31/2 .15 .05/2],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Vis Offset',...
%             'tag','vis_offset2text',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.32+dd .31/2 .08 .05/2],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.vis_offset2,...
%        	    'tag','vis_offset2',...
%         	'callback','update_set_flex;'); 
        
        %% STIM POSITION CONTROLS
        
        subplot (2,2,2);
        axis ([-40 40 -40 20])
        grid on
        title ('Position Controls','FontWeight','bold','FontSize',12)
        hold
        pos_plots(1)=plot (snd.flex_pos1(1),snd.flex_pos1(2),'diamondb','MarkerSize',15,'LineWidth',5);
        pos_plots(2)=plot (snd.flex_pos2(1),snd.flex_pos2(2),'diamondr','MarkerSize',15,'LineWidth',5);
        hold off
    
        %Map Peaks
        uicontrol ('style','pushbutton',...
            'units','normalized',...
            'position', [.65 .48 .2 .05],...
            'horizontalalignment','center',...
            'string','Generate WA map',...
            'fontweight', 'bold', ...
            'fontsize', 10,...
            'backgroundcolor', c_green,...
            'callback','set_WA_map');
        
        %Set Positions - X Y label
        uicontrol('style','text',...
            'units','normalized',...
            'position', [.715 .42 .15 .025],...
            'backgroundcolor',c_yellow,...
            'string','X',...
            'fontweight','bold',...
            'tag','vis_offset2text',...
            'horizontalalignment','left');
        uicontrol('style','text',...
            'units','normalized',...
            'position', [.765 .42 .15 .025],...
            'backgroundcolor',c_yellow,...
            'string','Y',...
            'fontweight','bold',...
            'tag','vis_offset2text',...
            'horizontalalignment','left');
        
        %Set Positions - Position 1
        uicontrol('style','text',...
            'units','normalized',...
            'position', [.6 .40 .15 .025],...
            'backgroundcolor',c_yellow,...
            'ForegroundColor',[0 0 1],...
            'FontWeight','bold',...
            'string','Vis Stim 1',...
            'tag','vis_offset2text',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','normalized',...
            'position', [.7 .40 .04 .025],...
            'backgroundcolor',c_yellow,...
            'horizontalalignment','left',...
            'string',snd.flex_pos1(1),...
            'tag','flex1_x',...
            'callback','update_set_flex;');
        uicontrol('style','edit',...
            'units','normalized',...
            'position', [.75 .40 .04 .025],...
            'backgroundcolor',c_yellow,...
            'horizontalalignment','left',...
            'string',snd.flex_pos1(2),...
            'tag','flex1_y',...
            'callback','update_set_flex;');
        
        %Set Positions - Position 2
        uicontrol('style','text',...
            'units','normalized',...
            'position', [.6 .37 .15 .025],...
            'backgroundcolor',c_yellow,...
            'ForegroundColor',[1 0 0],...
            'FontWeight','bold',...
            'string','Vis Stim 2',...
            'tag','vis_offset2text',...
            'horizontalalignment','left');
        uicontrol('style','edit',...
            'units','normalized',...
            'position', [.7 .37 .04 .025],...
            'backgroundcolor',c_yellow,...
            'horizontalalignment','left',...
            'string',snd.flex_pos2(1),...
            'tag','flex2_x',...
            'callback','update_set_flex;');
        uicontrol('style','edit',...
            'units','normalized',...
            'position', [.75 .37 .04 .025],...
            'backgroundcolor',c_yellow,...
            'horizontalalignment','left',...
            'string',snd.flex_pos2(2),...
            'tag','flex2_y',...
            'callback','update_set_flex;');
        
%         %Set Positions - Aud   NOT DOING INDIVIDUALIZED POSITIONS
%         uicontrol('style','text',...
%             'units','normalized',...
%             'position', [.6 .34 .15 .025],...
%             'backgroundcolor',c_yellow,...
%             'string','Aud Stim',...
%             'tag','vis_offset2text',...
%             'horizontalalignment','left');
%         uicontrol('style','edit',...
%             'units','normalized',...
%             'position', [.7 .34 .04 .025],...
%             'backgroundcolor',c_yellow,...
%             'horizontalalignment','left',...
%             'string',snd.flex_pos_a1(1),...
%             'tag','aud_x',...
%             'callback','update_set_flex;');
%         uicontrol('style','edit',...
%             'units','normalized',...
%             'position', [.75 .34 .04 .025],...
%             'backgroundcolor',c_yellow,...
%             'horizontalalignment','left',...
%             'string',snd.flex_pos_a1(2),...
%             'tag','aud_y',...
%             'callback','update_set_flex;');
        
            
            
        %% Run Button
        uicontrol('style','pushbutton',...
            'units','normalized',...
            'position', [.4 0.02 .2 .08],...
            'horizontalalignment','center',...
            'string','RUN FlexStim',...
            'fontweight', 'bold', ...
            'fontsize', 10,...
            'backgroundcolor', c_green,...
            'callback','flex_wrap');
        
        %% close button
        uicontrol('style','pushbutton',...
            'units','normalized',...
            'position', [.85 0.02 .13 .08],...
            'horizontalalignment','center',...
            'string','CLOSE',...
            'fontweight', 'bold', ...
            'fontsize', 10,...
            'backgroundcolor', c_red,...
            'callback','closesetflex');
        
%         %% update button
%         uicontrol('style','pushbutton',...
%             'units','normalized',...
%             'position', [.85 .1 .13 .08],...
%             'horizontalalignment','center',...
%             'backgroundcolor', c_red,...
%             'fontweight', 'bold', ...
%             'fontsize', 10,...
%             'string','Update',...
%             'callback','update_set_flex_display');
        
%         %% default button
%         uicontrol('style','pushbutton',...
%             'units','normalized',...
%             'position', [.85 0.02 .13 .08],...
%             'backgroundcolor', c_red,...
%             'horizontalalignment','center',...
%             'string','Defaults',...
%             'fontsize', 10,...
%             'fontweight', 'bold', ...           
%             'callback','get_setsnd_defaults');
	

%         %%other %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         uicontrol('style','text',...
%         	'units','normalized',...
%         	'position', [.35 .86 .1 .08],...%[.7 .3 .10 .1]
%         	'backgroundcolor',c_yellow,...
%         	'string','Other',...
%         	'horizontalalignment','center',...
%         	'fontweight','bold',...
%         	'fontsize',12);
% 	    
% 
%         
%         %%%%% set AM choice
% 	
% 	    shift1=.4;
%         shift2=.45;    
%         
%         uicontrol('style','popup',...
%        	    'units','normalized',...
%        	    'position', [.72-shift1 .36+shift2 .08 .05],...
%        	    'backgroundcolor',c_yellow,...
%             'fontsize',8,...
%             'string', snd.AMchoices,...
%             'value', snd.AMtype,...
%             'tag', 'noAM',...
%             'callback', 'update_set_flex',...
%        	    'horizontalalignment','left');
%         %% set depth_mod
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.72-shift1 .25+shift2 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Mod depth',...
%        	    'horizontalalignment','left');
%         uicontrol('style','text',...
%         	'units','normalized',...
%         	'position', [.8-shift1 .29+shift2 .035 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string','Aud'); 
%         uicontrol('style','text',...
%         	'units','normalized',...
%         	'position', [.845-shift1 .29+shift2 .035 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string','Vis'); 
% 	
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.8-shift1 .25+shift2 .035 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.mod_depth,...
%        	    'tag','mod_depth',...
%         	'callback','update_set_flex;'); 
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.845-shift1 .25+shift2 .035 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.amp_mod_vis,...
%        	    'tag','amp_mod_vis',...
%         	'callback','update_set_flex;'); 
% 	
%         %% set Freq_mod
%         uicontrol('style','text',...
%        	    'units','normalized',...
%        	    'position', [.72-shift1 .18+shift2 .15 .05],...
%        	    'backgroundcolor',c_yellow,...
%        	    'string','Mod Hz',...
%        	    'horizontalalignment','left');
%         uicontrol('style','edit',...
%         	'units','normalized',...
%         	'position', [.8-shift1 .18+shift2 .08 .05],...
%         	'backgroundcolor',c_yellow,...
%         	'horizontalalignment','left',...
%       		'string',snd.Freq_mod,...
%        	    'tag','Freq_mod',...
%         	'callback','update_set_flex;');
%         
             flex_on_off;  %% this function disables sound/vis tags that aren't being used, and vice versa 

return;

%% CODE DUMP %%%%%%%%%%%%%%%%%%%

