function check_TF(RPVDS_path,RP1name,RP2name,RA16name,atten_num)
    % taken from Ilana's measure_HRTFs function

global cal RP_1 RP_2 pa5_1 pa5_2 pa5_3 pa5_4 RA_16  zbus right_fig left_fig menu_fig;


% loadTDT(pwd,'rp1_check_cal','rp2_measure_TF','',4) 

rpvds_path=strcat(pwd,'\..\Equalization'); %changed the path to these files DJT 7/2/2014
loadTDT(rpvds_path,'rp1_check_cal','rp2_measure_TF','',2) 
% loadTDT(pwd,'rp1_check_cal','rp2_measure_TF','',2) 


% % % design band pass filter
n=70;
f=[0 cal.min*1000/(cal.fs/2) cal.max*1000/(cal.fs/2) 1];
amp=[0 1 0];
myup=[0.001 1.01 0.001];
mylow=[-0.01 0.99 -0.01];
b=fircls(n,f,amp,myup,mylow);
% load band pass filter
%Can't seem to write any of this stuff to the specified RP_1 COF routines,
%even though they are loaded to the processor.  Not sure whats up - DJT
%7/1/14
if invoke(RP_1,'WriteTagV','filter',0,b)  
    fprintf(1,'\n%s\n',['Noise band filter successfully loaded'])
else
    e='Noise band filter incorrectly loaded'
end

% load all the other parameters to TDT (except for equalization file)
if invoke(RP_1,'SetTagVal','buffer_size',cal.buffer_size); %changed from RP_2 to RP_1 DJT 3/13/2012
else
    'buffer size incorrectly set'
end
if invoke(RP_1,'SetTagVal','amp',cal.amp);
else
    'amp  incorrectly set'
end

if invoke(pa5_1,'SetAtten',cal.atten);
else
    e='Right AP5 error'
end

if invoke(pa5_2,'SetAtten',cal.atten);
else
    e='Right AP5 error'
end

% if invoke(pa5_3,'SetAtten',100);
% else
%     e='Right AP5 error'
% end
% 
% if invoke(pa5_4,'SetAtten',100);
% else
%     e='Right AP5 error'
% end



screen=get(0,'screensize');
figure('position',[500 500 screen(3)/2.5 screen(4)/3.5],...
    'menubar','none','color',cal.c_yellow,'tag','menu');
    

uicontrol('style','text',...
    'units','normalized',...
    'position', [.2 .75 .5 .1],...
    'horizontalalignment','left',...
    'backgroundcolor', cal.c_yellow,...
    'string','Check right earphone',...
    'fontweight','bold',...
    'fontsize', 14);

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.65 .74 .14 .11],...
    'horizontalalignment','right',...
    'backgroundcolor', cal.c_green,...
    'string','GO',...
    'fontweight','bold',...
    'fontsize', 18,...
    'callback','cal.earphone=1;load_sound;');

uicontrol('style','text',...
    'units','normalized',...
    'position', [.2 .55 .5 .1],...
    'horizontalalignment','left',...
    'backgroundcolor', cal.c_yellow,...
    'string','Check left earphone',...
    'fontweight','bold',...
    'fontsize', 14);

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.65 .56 .14 .11],...
    'horizontalalignment','right',...
    'backgroundcolor', cal.c_green,...
    'string','GO',...
    'fontweight','bold',...
    'fontsize', 18,...
    'callback','cal.earphone=0;load_sound;');


uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.2 .25 .6 .11],...
    'horizontalalignment','center',...
    'backgroundcolor', cal.c_green,...
    'string','Compare earphones',...
    'fontweight','bold',...
    'fontsize', 18,...
    'callback','check_filters_plot; close_windows;');  


fprintf(1,'\n\nHOW TO CONNECT THE CABLES WHEN USING THIS PROGRAM:\n')
fprintf(1,'Output 1 of RP_1 goes to the PA5 input of the appropriate earphone\n')
fprintf(1,'Output 2 of RP_1 goes to input 2 of RP_1\n')%changed from RP_2 to RP_1 DJT 3/13/2012
fprintf(1,'Input 1 of RP_1 comes from the microphone amplifier\n'); %changed from RP_2 to RP_1 DJT 3/13/2012

return;
