global cal RP_1 RP_2 pa5_1 pa5_2 pa5_3 pa5_4 RA_16  zbus;

screen=get(0,'screensize');
h=figure('position',[500 500 screen(3)/2.5 screen(4)/3.5],...
    'menubar','none','color',cal.c_yellow,...
    'tag','start');
uicontrol('style','text',...
    'units','normalized',...
    'position', [0.05 0.6 0.9 0.3],...
    'backgroundcolor',cal.c_yellow,...
    'string','Import Equalization File:',...
    'horizontalalignment','left',...
    'fontweight','bold',...
    'fontsize',14);


uicontrol('style','text',...
    'units','normalized',...
    'position', [0.05 0.45 0.95 0.3],...
    'backgroundcolor',cal.c_yellow,'string','The appropriate equalization filters will be loaded using the program file path.',...
    'horizontalalignment','left',...
    'fontweight','bold','fontsize',10);
uicontrol('style','text',...
    'units','normalized',...
    'position', [0.05 0.25 0.95 0.3],...
    'backgroundcolor',cal.c_yellow,'string','Find the program you will run ("aud_space" or "AV_space"): ',...
    'horizontalalignment','left',...
    'fontweight','bold','fontsize',10);
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [0.3 0.35 0.2 0.1],...
    'horizontalalignment','right',...
    'string','Browse',...
    'fontweight','bold',...
    'callback','file_browse;');  % 'cal.earphone=0;file_browse;');  


uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [0.05 0.05 0.55 0.1],...
    'string','Load filters used by this program',...
    'fontweight','bold','fontsize',12,...
    'horizontalalignment','left',...
    'callback','open_eq_file; close(h);');   % could call main_menu again, but it should still be open
