function main_menu()
    global cal RP_1 RP_2 pa5_1 pa5_2 pa5_3 pa5_4 RA_16  zbus;

    screen=get(0,'screensize');
    h=figure('position',[500 500 screen(3)/2-100 screen(4)/4],...
        'menubar','none','color',cal.c_yellow,...
        'tag','start');

    uicontrol('style','text',...
        'units','normalized',...
        'position', [0.05 0.6 0.3 0.3],...
        'backgroundcolor',cal.c_yellow,...
        'string','Equalization Options:',...
        'horizontalalignment','left',...
        'fontweight','bold',...
        'fontsize',14);
    uicontrol('style','text',...
        'units','normalized',...
        'position', [0.38 0.1 0.001 0.8],...
        'backgroundcolor',[0,0,0]);



    uicontrol('style','text',...
        'units','normalized',...
        'position', [0.45 0.7 0.05 0.1],...
        'backgroundcolor',cal.c_yellow,'string','1.',...
        'horizontalalignment','right',...
        'fontweight','bold','fontsize',12);
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [0.5 0.7 0.4 0.1],...
        'horizontalalignment','center',...
        'string','Load filters (to check)',...
        'fontweight','bold',...
        'callback','import_eq_files');  


    uicontrol('style','text',...
        'units','normalized',...
        'position', [0.45 0.5 0.05 0.1],...
        'backgroundcolor',cal.c_yellow,'string','2.',...
        'horizontalalignment','right',...
        'fontweight','bold','fontsize',12);
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [0.5 0.5 0.4 0.1],...
        'horizontalalignment','center',...
        'string','Check filters',...
        'fontweight','bold',...
        'callback','check_TF');  


    uicontrol('style','text',...
        'units','normalized',...
        'position', [0.45 0.3 0.05 0.1],...
        'backgroundcolor',cal.c_yellow,'string','3.',...
        'horizontalalignment','right',...
        'fontweight','bold','fontsize',12);
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [0.5 0.3 0.4 0.1],...
        'string','Create new filters',...
        'fontweight','bold',...
        'horizontalalignment','center',...
        'callback','measure_TF');



    uicontrol('style','text',...
        'units','normalized',...
        'position', [0.45 0.1 0.05 0.1],...
        'backgroundcolor',cal.c_yellow,'string','4.',...
        'horizontalalignment','right',...
        'fontweight','bold','fontsize',12);
    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [0.5 0.1 0.4 0.1],...
        'horizontalalignment','center',...
        'string','Save filters',...
        'fontweight','bold',...
        'callback','export_eq_files');  


    uicontrol('style','pushbutton',...
        'units','normalized',...
        'position', [0.9 0.9 0.1 0.1],...
        'horizontalalignment','center',...
        'string','exit',...
        'fontweight','bold',...
        'callback','clear all;close all');  

return
