function measure_TF(RPVDS_path,RP1name,RP2name,RA16name,atten_num)
    % taken from Ilana's measure_HRTFs function

global cal RP_1 RP_2 pa5_1 pa5_2 pa5_3 pa5_4 RA_16  zbus right_fig left_fig menu_fig;


rpvds_path=strcat(pwd,'\..\Equalization');

loadTDT(rpvds_path,'rp1_measure_TF','rp2_measure_TF','',2)  %changed the path to these files DJT 7/2/2014
% loadTDT(pwd,'rp1_measure_TF','rp2_measure_TF','',4)  

% % % design band pass filter
n=70;
f=[0 cal.min*1000/(cal.fs/2) cal.max*1000/(cal.fs/2) 1];
amp=[0 1 0];
myup=[0.001 1.01 0.001];
mylow=[-0.01 0.99 -0.01];
b=fircls(n,f,amp,myup,mylow);

% freqz(b,1,n);

% load band pass filter

% invoke (RP_1,'Halt') %added DJT 7/2/2014 ... don't think I need to do
% this because it shouldn't be running

if invoke(RP_1,'WriteTagV','filter',0,b)
    fprintf(1,'\n%s\n',['Noise band filter successfully loaded'])
else
    e='Filter incorrectly loaded'
end

if invoke(RP_1,'SetTagVal','buffer_size',cal.buffer_size); %%changing to run w/ single RP2 DJT 3/13/2012
else
    'buffer size incorrectly set'
end

if invoke(RP_1,'SetTagVal','amp',cal.amp);
else
    'amp  incorrectly set'
end

% invoke (RP_1,'run') %added DJT 7/2/2014

if invoke(pa5_1,'SetAtten',cal.atten);
else
    e='Right AP5 error'
end

if invoke(pa5_2,'SetAtten',cal.atten);
else
    e='Right AP5 error'
end

% Only have 2 PA5s - DJT 7/2/2014
% if invoke(pa5_3,'SetAtten',100);
% else
%     e='Right AP5 error'
% end
% 
% if invoke(pa5_4,'SetAtten',100);
% else
%     e='Right AP5 error'
% end

screen=get(0,'screensize');
figure('position',[500 500 screen(3)/2.5 screen(4)/3.5],...
    'menubar','none','color',cal.c_yellow,'tag','menu');
    

uicontrol('style','text',...
    'units','normalized',...
    'position', [.2 .75 .5 .1],...
    'horizontalalignment','center',...
    'backgroundcolor', cal.c_yellow,...
    'string','Measure right earphone',...
    'fontweight','bold',...
    'fontsize', 14);

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.7 .77 .14 .11],...
    'horizontalalignment','center',...
    'backgroundcolor', cal.c_green,...
    'string','GO',...
    'fontweight','bold',...
    'fontsize', 18,...
    'callback','cal.earphone=1;play_sound;');

uicontrol('style','text',...
    'units','normalized',...
    'position', [.2 .55 .5 .1],...
    'horizontalalignment','center',...
    'backgroundcolor', cal.c_yellow,...
    'string','Measure left earphone',...
    'fontweight','bold',...
    'fontsize', 14);

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.7 .57 .14 .11],...
    'horizontalalignment','center',...
    'backgroundcolor', cal.c_green,...
    'string','GO',...
    'fontweight','bold',...
    'fontsize', 18,...
    'callback','cal.earphone=0;play_sound;');


uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.3 .27 .5 .11],...
    'horizontalalignment','left',...
    'backgroundcolor', cal.c_green,...
    'string','Create filters',...
    'fontweight','bold',...
    'fontsize', 18,...
    'callback','close_windows;design_filter');  

fprintf(1,'\n\nHOW TO CONNECT THE CABLES WHEN USING THIS PROGRAM:\n')
fprintf(1,'Output 1 of RP_1 goes to the PA5 input of the appropriate earphone\n')
fprintf(1,'Output 2 of RP_1 goes to input 2 of RP_1\n') %%changing to run w/ single RP2 DJT 3/13/2012
fprintf(1,'Input 1 of RP_1 comes from the microphone amplifier\n'); %%changing to run w/ single RP2 DJT 3/13/2012

return;


