function set_dot_product
global snd rec screen_offset chan_select


c_yellow=[.95, .95, .7];
c_green=[.5,.58,.5];
c_red=[.7 .4 .4];

num_chan=max(snd.datachan);
chan_select = zeros(1,num_chan);

%%open a new window
myscreen=get(0,'screensize');
figure('position',[(myscreen(3)/2+screen_offset),(myscreen(4)/2-380),300,600],'menubar','none','tag','JoeSound_win', 'color', c_yellow);

%% Channel Select Buttons
for i=1:num_chan;
    uicontrol('style','text',...
        'units','normalized',...
        'position', [.05 .8/num_chan*(num_chan+1-i)+.08 .4 .1],...
        'backgroundcolor',c_yellow,...
        'string',strcat('Channel ', num2str(i)),...
        'horizontalalignment','center',...        
        'fontsize',12);
    
    uicontrol('style','checkbox',...
        'units','normalized',...
        'position', [.4 .8/num_chan*(num_chan+1-i)+.14 .1 .05],...
        'backgroundcolor',c_yellow,...
        'fontsize',8,...
        'tag', strcat('chan',num2str(i)),...
        'callback', 'update_set_dotproduct',...
        'horizontalalignment','left');
end

%% Select Buttons

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.6 .9 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Select All',...
    'fontsize',12,...
    'tag', 'select_all',...
    'callback', 'set_noisecorr_select_all',...
    'horizontalalignment','left');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.6 .85 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Deselect All',...
    'fontsize',12,...
    'tag', 'deselect_all',...
    'callback', 'set_noisecorr_deselect_all',...
    'horizontalalignment','left');

%% Run Button
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.1 .025 .8 .1],...
    'horizontalalignment','center',...
    'string','Do it!',...
    'fontweight', 'bold', ...
    'fontsize', 10,...
    'backgroundcolor', c_red,...
    'callback','DotProduct_Wrap');
