function set_noisecorr
global snd screen_offset chan_select save_corr select_all deselect_all pre_post

save_corr=0;
pre_post=[1,0,0];
%pre_post(1)=correlate adjusted data(pre minus post)
%pre_post(2)=correlate data just from the pre-period
%pre_post(3)=correlate data just form the post_period

addpath ('C:\Users\debellolab\Desktop\Doug\DATA\OwlLand_8chan\DataAnalysis')

c_yellow=[.95, .95, .7];
c_green=[.5,.58,.5];
c_red=[.7 .4 .4];

num_chan=max(snd.datachan);
chan_select = zeros(1,num_chan);

%%open a new window
myscreen=get(0,'screensize');
figure('position',[(myscreen(3)/2+screen_offset),(myscreen(4)/2-380),300,600],'menubar','none','tag','JoeSound_win', 'color', c_yellow);

%% Channel Select Buttons
for i=1:num_chan;
    uicontrol('style','text',...
        'units','normalized',...
        'position', [.05 .8/num_chan*(num_chan+1-i)+.08 .4 .1],...
        'backgroundcolor',c_yellow,...
        'string',strcat('Channel ', num2str(i)),...
        'horizontalalignment','center',...        
        'fontsize',12);
    
    uicontrol('style','checkbox',...
        'units','normalized',...
        'position', [.4 .8/num_chan*(num_chan+1-i)+.14 .1 .05],...
        'backgroundcolor',c_yellow,...
        'fontsize',8,...
        'tag', strcat('chan',num2str(i)),...
        'callback', 'update_set_noisecorr',...
        'horizontalalignment','left');
end

%% Select Buttons

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.6 .9 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Select All',...
    'fontsize',12,...
    'tag', 'select_all',...
    'callback', 'set_noisecorr_select_all',...
    'horizontalalignment','left');

uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.6 .85 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','Deselect All',...
    'fontsize',12,...
    'tag', 'deselect_all',...
    'callback', 'set_noisecorr_deselect_all',...
    'horizontalalignment','left');

%% Analysis Types

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.6 .75 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','post-pre',...
    'fontsize',12,...
    'tag', 'pre_and_post',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');

set (findobj(gcf,'tag','pre_and_post'),'Value',1);

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.6 .7 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','pre alone',...
    'fontsize',12,...
    'tag', 'pre_alone',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.6 .65 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','post alone',...
    'fontsize',12,...
    'tag', 'post_alone',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');

%% Figure Controls

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.6 .55 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','save .mat',...
    'fontsize',12,...
    'tag', 'save_mat',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.6 .5 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','save .tif',...
    'fontsize',12,...
    'tag', 'save_tif',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');
set (findobj(gcf,'tag','save_tif'),'Value',1);

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.6 .45 .4 .05],...
    'backgroundcolor',c_yellow,...
    'string','auto close',...
    'fontsize',12,...
    'tag', 'close_figs',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');
set (findobj(gcf,'tag','close_figs'),'Value',1);

uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.55 .4 .45 .05],...
    'backgroundcolor',c_yellow,...
    'string','suppress figures',...
    'fontsize',12,...
    'tag', 'suppress_figs',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');


%% Save Box
uicontrol('style','text',...
    'units','normalized',...
    'position', [.6 .15 .3 .1],...
    'backgroundcolor',c_yellow,...
    'string','save?',...
    'horizontalalignment','center',...
    'fontsize',12);
uicontrol('style','checkbox',...
    'units','normalized',...
    'position', [.9 .185 .1 .1],...
    'backgroundcolor',c_yellow,...
    'fontsize',8,...
    'tag', 'save_corr',...
    'callback', 'update_set_noisecorr',...
    'horizontalalignment','left');
set (findobj(gcf,'tag','save_corr'),'Value',1);

%% Run Button
uicontrol('style','pushbutton',...
    'units','normalized',...
    'position', [.1 .025 .8 .1],...
    'horizontalalignment','center',...
    'string','Do it!',...
    'fontweight', 'bold', ...
    'fontsize', 10,...
    'backgroundcolor', c_red,...
    'callback','NoiseCorr_Wrap');
